elastic/apm-agent-rum-js

docs/index.asciidoc, docs/intro.asciidoc
Use the shared attributes provided
by elastic/docs for linking to other
product docs, forums, etc.
Requires https://github.com/elastic/docs/pull/370
=> docs: use shared attributes

docs/index.asciidoc, docs/intro.asciidoc, docs/sourcemap.asciidoc
Versions 1.x docs links to Elastic stack v6.4 per https://github.com/elastic/apm/issues/19
=> Docs: version cross document links in 1.x

package-lock.json, package.json, scripts/release-github.js, scripts/upload-assets.js
+ Created a release via this script - 
https://github.com/elastic/apm-agent-js-base/releases/tag/v2.2.0
TODO
+ [x] have to exclude license and map files from getting uploaded
+ [x] Update the docs https://github.com/elastic/apm-agent-js-base/pull/118 with release version
=> chore: add script to create & upload release assets

package.json, packages/rum/package.json, scripts/release-github.js
+ part of elastic/apm-agent-js-base#146 
+ This happens after we do `lerna publish` which is covered in another PR elastic/apm-agent-js-base#164 
+ fixes elastic/apm-agent-js-base#157 
+ The tagging issue should not be a problem anymore since we rely on tag creation via lerna /cc @jahtalab
=> chore: fix release script for github artificats

packages/rum-core/src/common/constants.js, packages/rum-core/src/performance-monitoring/capture-hard-navigation.js, packages/rum-core/src/performance-monitoring/transaction-service.js, packages/rum-core/test/fixtures/navigation-timing-span-snapshot.js, packages/rum-core/test/fixtures/resource-entries.js, packages/rum-core/test/performance-monitoring/capture-hard-navigation.spec.js
+ Turned out to be a bit more extensive that I thought, There are multiple resource types that are being captured by `perf.getEntriesByType("resource")`.. List is specified here - https://github.com/web-platform-tests/wpt/blob/b0020d5df18998609b38786878f7a0b92cc680aa/resource-timing/resource_initiator_types.html#L93
+ I have added as check to create Spans for all known resource types except (embed, video, audio etc) which does not make much sense since its uncommon, We can support it in future. 
+ Refactored the code a bit to look nicer. 
+ fixes https://github.com/elastic/apm-agent-js-base/issues/161
=> feat(rum-core): measure all resource entries in page load

.gitignore, dev-utils/dep-info.js, packages/rum-core/NOTICE.txt, packages/rum-core/README.md, packages/rum/NOTICE.txt
+ Generate notices for all packages. 
+ Notice and Readme is automatically published with NPM, so no need of including in files array in package.json
=> chore: modify notice generation script [skip ci]

packages/rum-core/src/common/apm-server.js, packages/rum-core/src/performance-monitoring/capture-hard-navigation.js, packages/rum-core/src/performance-monitoring/performance-monitoring.js, packages/rum-core/src/performance-monitoring/transaction.js
+ Resource timing entries name have fully resolved URL as part of the SPEC and we dont really need to  parse them again based on the window base URL. 
+ The context information is sent only when the Entry Name is different from Span name -> Happens when the resource contains query strings in URL. small optimisation for reducing the payload to APM server.
=> perf(rum-core): avoid url parsing on resource timing entries

docs/configuration.asciidoc, packages/rum-core/src/common/apm-server.js, packages/rum-core/src/common/config-service.js, packages/rum-core/src/common/utils.js, packages/rum-core/test/common/apm-server.spec.js
+ fixes elastic/apm-agent-js-base#48 
+ Users can add an option to override the environment where the service being monitored is deployed. Add the doc for the same.
=> feat(rum-core): add service env to metadata payload

dev-utils/test-config.js
+ We were defaulting to `http://localhost:8200` for . server url which was wrong and caught by https://github.com/elastic/apm-integration-testing/pull/370
=> chore(rum): e2e bundles should point to correct apm server url

packages/rum/package.json
+ This is a bug, We should allow the users of our library to do necessary optimisations(Preferring ES6 or ES5) on the lib.
=> BREAKING CHANGE(rum): resolve main field to source file

CONTRIBUTING.md, dev-utils/karma.js, dev-utils/run-script.js, package.json, packages/rum-core/package.json, packages/rum/package.json, packages/rum/run-script.js, packages/rum/test/e2e/.babelrc.js, packages/rum/test/e2e/general-usecase/app.e2e-spec.js, packages/rum/test/e2e/standalone-html/app.e2e-failsafe.js, packages/rum/test/e2e/standalone-html/app.e2e-spec.js, packages/rum/test/e2e/standalone-html/index.html, packages/rum/test/e2e/standalone-html/opentracing.html, packages/rum/wdio-failsafe.conf.js, packages/rum/wdio.conf.js
Dropping the support for IE 10 and android 4* versions. Bundling configurations and testing environments are changed to reflect the same
+ fixes https://github.com/elastic/apm-agent-js-base/issues/132
+ Unit and E2E Tests now use single saucelabs tunnel to improve the test speed and also parallized the tests for supported/unsupported browsers.
=> BREAKING CHANGE: move IE 10 and Android 4 to unsupported list

CHANGELOG.md, packages/rum-core/CHANGELOG.md, packages/rum/CHANGELOG.md
+ The breaking changes commit was sqaushed and the commit body was all over the changelog.  Other breaking changes commits did not have commit . body and it wasn't captured in breaking changes 
+ . Updated the master changelog manually till we find a good solution to automate that.
=> Update changelog 4.0.0 [skip ci]

.travis.yml
Grouping the tests under one stage would take advantage of our concurrency setting.
Also, this allows the bundle size check to fail.
=> chore: group lint and bundle size under check stage

packages/rum/run-script.js, packages/rum/test/e2e/integration-test.js, packages/rum/test/node/integration-test.node-spec.js
+ When the Integration tests timeout, we get unhandled promise rejection warnings, This PR fixes that and instead logs error to stdout.
=> chore(rum): unhandled promise rejection in integration test

dev-utils/karma.js, dev-utils/test-config.js, dev-utils/webdriver.js, packages/rum-core/test/common/fetch-patch.spec.js, packages/rum-core/test/common/patch.js, packages/rum/test/e2e/general-usecase/app.js, packages/rum/test/e2e/manual-timing/app.e2e-spec.js, packages/rum/test/e2e/react/app.e2e-spec.js, packages/rum/test/e2e/react/app.jsx, packages/rum/test/e2e/react/main-component.jsx, packages/rum/test/e2e/react/webpack.config.js, packages/rum/wdio-failsafe.conf.js, packages/rum/wdio.conf.js
+ fixes elastic/apm-agent-rum-js#205 
+ Unit and E2E tests are run on same set of browsers to catch different bugs during E2E.
+ Safari 11.0 - 11.3 has a bug in fetch spec, window.fetch() without params doesn't get rejected. 
+ Ios emulators have bug when setting script timeout in appium. Removed them from the E2E tests till new appium version is available in sauce labs
+ `window.URL` is broken in IE 11 - it took me 2 hours to figure out why this happens and have no clue till i remote debugged IE 11. 
+ linted .jsx files with proper fixes. 
+ Remove chrome 46 and firefox 42  since the global usage was 0% and replace with other versions which has some usage stats.
=> chore(rum): update browser versions for android and ios in tests

packages/rum/wdio.conf.js
+ The logs on the tests gets polluted and it's really hard to identify the issue on failures. Now the logs are printed to console only on failing tests.
=> chore(rum): print browser logs only on e2e test failures

dev-utils/karma.js, dev-utils/test-config.js, package-lock.json, package.json, packages/rum-core/src/common/apm-server.js, packages/rum-core/src/common/config-service.js, packages/rum-core/test/common/apm-server.spec.js, packages/rum/babel-version-plugin.js, packages/rum/package.json, packages/rum/src/apm-base.js, packages/rum/webpack.config.js
+ Two reasons
- Its possible to break the APM UI by simply changing the name of the agent 
- Be consistent with other agents
+ One more issue with our current approach is that, When users use our package directly instead of our distribution, Our agent name will never be changed unless the user builds it locally using our webpack config due to the way we replace the version using string-replace-load which is a bug. 
```js
const rumjs = require('elastic-apm-rum')
// application code
// user builds the bundle using webpack, parcel or whatever toolchain
// bundle would still contains
agentVersion: '%%agent-version%%',
```
=> fix(rum-core): hardcode agent name and version in service metadata

docs/intro.asciidoc
CORS documentation! Closes #66:
---
~I have some questions:~
* ~Where can I find the cross-origin headers to complete the last checkbox above?~
* ~It's not immediately clear to me if any configuration needs to be done in the rum agent itself, or if all configuration is done in the Server?~
* ~Should we mention the `distributeTracingOrigins` config option here as well? If so, what's important?~
=> [docs] CORS documentation

packages/rum-core/src/common/apm-server.js, packages/rum-core/src/common/config-service.js, packages/rum-core/src/common/constants.js, packages/rum-core/src/common/truncate.js, packages/rum-core/src/common/utils.js, packages/rum-core/src/error-logging/error-logging.js, packages/rum-core/src/performance-monitoring/performance-monitoring.js, packages/rum-core/test/common/apm-server.spec.js, packages/rum-core/test/common/config-service.spec.js, packages/rum-core/test/common/truncate.spec.js, packages/rum-core/test/common/utils.spec.js, packages/rum-core/test/error-logging/error-logging.spec.js, packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
+ Alternative implementation of https://github.com/elastic/apm-agent-rum-js/pull/199
+ fixes elastic/apm-agent-rum-js#61 
+ Minor refactoring on the corresponding files. 
+ All the undefined and null values are removed from the server payload to reduce the payload size. This is done using required field in truncation.
=> fix(rum-core): apply truncation on keyword fields in payload

packages/rum-core/src/common/truncate.js
instead of falsy values when checking required fields. 
Checking for falsy doesn't work for `0` which is a valid value for a required field but we instead try to use the placeholder.
=> fix(rum-core): In truncate check for empty values

package-lock.json, package.json
+ part of https://github.com/elastic/apm-agent-rum-js/issues/211
+ lerna 3.14.0 supports prompting for OTP during npm publish.
=> chore(rum): update lerna that fixes the 2FA on publish [skip ci]

packages/rum-core/src/common/constants.js, packages/rum-core/src/common/patching/history-patch.js, packages/rum-core/src/opentracing/tracer.js, packages/rum-core/src/performance-monitoring/performance-monitoring.js, packages/rum-core/src/performance-monitoring/transaction-service.js, packages/rum-core/src/performance-monitoring/transaction.js, packages/rum-core/test/common/history-patch.spec.js, packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js, packages/rum-core/test/performance-monitoring/transaction-service.spec.js, packages/rum-core/test/performance-monitoring/transaction.spec.js, packages/rum/test/specs/apm-base.spec.js
This is part of the effort to [capture route change transactions](https://github.com/elastic/apm-agent-rum-js/issues/90). 
- patch history API
- refactoring of `TransactionService.startTransaction`
- introduce transaction reusability
=> feat(rum-core): capture history.pushState calls as transactions

docs/agent-api.asciidoc, docs/span-api.asciidoc, docs/transaction-api.asciidoc, packages/rum-core/src/common/config-service.js, packages/rum-core/src/common/utils.js, packages/rum-core/src/opentracing/span.js, packages/rum-core/src/performance-monitoring/span-base.js, packages/rum-core/test/common/config-service.spec.js, packages/rum-core/test/common/utils.spec.js, packages/rum-core/test/opentracing/opentracing.spec.js, packages/rum-core/test/performance-monitoring/span-base.spec.js, packages/rum/src/apm-base.js, packages/rum/test/e2e/general-usecase/app.js, packages/rum/test/specs/apm-base.spec.js, packages/rum/test/specs/index.spec.js
+ first step of elastic/apm-agent-rum-js#215 
+ Opentracing `addTags` still works and under the hood calls span.addLabels for adding labels.
=> feat(rum): deprecate addTags in favor of addLabels

dev-utils/test-config.js, packages/rum/run-script.js, packages/rum/test/e2e/utils.js
+ fix #266 
+ We already print console logs when test fails, but to support older drivers/browsers, now extendedDebugging is enabled. Incase the browser logs are not printed, We can do a curl request to the below API to print to figure out the logs. 
```sh
curl https://<username>:<password>@eds.saucelabs.com/<testId>/console.json
```
+ set logging preferences for browser logs
+ do not truncate logs when process exits.
=> chore(rum): enable extended debugging and console logs for e2e tests

packages/rum-core/src/error-logging/error-logging.js, packages/rum-core/test/error-logging/error-logging.spec.js
+ fixes https://github.com/elastic/apm-agent-rum-js/issues/267
=> feat(rum-core): use error event instead of global onerror method

packages/rum-core/src/common/constants.js, packages/rum-core/src/performance-monitoring/span-base.js, packages/rum-core/src/performance-monitoring/span.js, packages/rum-core/src/performance-monitoring/transaction-service.js, packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js, packages/rum-core/test/performance-monitoring/transaction-service.spec.js
+ removed dead code from transaction service `sendPageLoadMetrics` which was only used in tests . and also refactored the async code. 
+ removed functions related to how we run async code with function context passed around, Not necessary anymore with arrow functions. Helps new contributors understand the code easier. 
+ Moved transaction name and type as constants. 
+ Extracted from other clean up PR to make review easier.
=> chore(rum-core): remove functions from transaction-service

packages/rum-core/src/performance-monitoring/span-base.js, packages/rum-core/src/performance-monitoring/transaction-service.js, packages/rum-core/test/performance-monitoring/span-base.spec.js, packages/rum/src/apm-base.js
+ Set the default name and type for all transaction and span and remove the check in other places on the codebase. 
+ Extracted from other PR elastic/apm-agent-rum-js#294
=> chore: use default name and type for transaction and spans

packages/rum-core/src/common/config-service.js, packages/rum-core/src/performance-monitoring/span-base.js, packages/rum-core/test/common/config-service.spec.js, packages/rum-core/test/opentracing/opentracing.spec.js, packages/rum-core/test/performance-monitoring/span-base.spec.js
+ fixes https://github.com/elastic/apm-agent-rum-js/issues/315
=> fix(rum:core): send labels via context.tags in the payload

packages/rum-core/src/common/truncate.js, packages/rum-core/src/common/utils.js, packages/rum-core/src/performance-monitoring/capture-hard-navigation.js, packages/rum-core/test/common/truncate.spec.js, packages/rum-core/test/common/utils.spec.js, packages/rum-core/test/fixtures/navigation-entries.js, packages/rum-core/test/performance-monitoring/capture-hard-navigation.spec.js, packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js, packages/rum-core/test/performance-monitoring/transaction-service.spec.js
+ fixes elastic/apm-agent-rum-js#190 
+ transfer_size - directly maps to the transferSize resource timing entry
+ encoded_body_size - maps to the encodedBodySize in resource timing entry.
=> feat(rum-core): add size & server timing information to traces

.ci/scripts/pull_and_build.sh, Jenkinsfile
- Sometimes if the infra is temporary down then the pipelines might fail. See [build](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fapm-agent-rum-mbp/detail/PR-322/6/pipeline/122)
```
[2019-07-12T14:14:14.216Z] Pulling elasticsearch (docker.elastic.co/elasticsearch/elasticsearch:6.6.0)...
[2019-07-12T14:14:32.360Z] Get https://docker.elastic.co/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
script returned exit code 1
```
- let's retry up to 3 times with a sleep time to pull and build the required docker images previously.
=> ci(jenkins): more resilient when infra is temporarily unreachable

Jenkinsfile, README.md, codecov.yml, dev-utils/docker-compose.yml, dev-utils/karma.js, package-lock.json, package.json, packages/rum-core/package.json, packages/rum-react/karma.conf.js, packages/rum-react/package.json, packages/rum/package.json
+ testing code coverage since we have Jenkins pipeline already integrated now. 
+ fixes #153 
- Publish to `https://codecov.io/gh/elastic/apm-agent-rum-js`
- https://github.com/elastic/apm-agent-rum-js/pull/322/commits/fa5a844063726348f24b6f8a59952f72258fefcb enable the coverage in the Jenkins pipeline.
- It does provide a new stage to validate the code coverage and push to codecov.io using the stack `7.0.0` and without any goal (as it will run for all the packages) rather than the whole configuration matrix of stacks and scopes.
- It does extend the puppeteer docker node to run the npm goal which has been specified in the `GOAL` env variable. Therefore, the same dockerised infra can be used for running `npm run test` and `npm run coverage`.
```
export STACK_VERSION=7.0.0
export …
```
=> chore(coverage): adding code coverage for all packages

Jenkinsfile
This is caused by https://github.com/jenkinsci/github-branch-source-plugin/pull/235
- ITs for the rum-js agent don't require the repo name as it does fetch the PRs too
- See https://github.com/elastic/apm-integration-testing/blob/edb0048bb0d3c79e8c8c9349bde7030762ddc7f6/docker/rum/Dockerfile#L23-L26
=> ci(jenkins): ITs for forked repos with different name is not supported

.ci/scripts/test.sh, Jenkinsfile, dev-utils/karma.js, package-lock.json, package.json
- Enable JUnit reporting in the Jenkins pipeline.
- See [this](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fapm-agent-rum-mbp%2FPR-323/detail/PR-323/2/tests/)
```
export STACK_VERSION=7.0.0
export APM_SERVER_URL='http://apm-server:8200'
export APM_SERVER_PORT='8200'
export GOAL="test"
export JENKINS_URL="https://jenkins.elastic.co/"
.ci/scripts/test.sh
```
=> ci(jenkins): enable junit reporting to be consumed by the pipeline

Jenkinsfile, dev-utils/docker-compose.yml, dev-utils/karma.js
- Export coverage as cobertura reports being exposed in the Jenkins pipeline.
See [here](https://apm-ci.elastic.co/job/apm-agent-rum/job/apm-agent-rum-mbp/view/change-requests/job/PR-332/2/cobertura/)
=> ci(jenkins): report cobertura in the pipeline

Jenkinsfile
- A way to add resilient in case of environmental issues as for instance it might happen what it just happened in one of the builds:
```
[2019-07-18T10:16:12.795Z] node-puppeteer         | + npm install puppeteer --unsafe-perm=true --allow-root
[2019-07-18T10:16:34.781Z] node-puppeteer         | 
[2019-07-18T10:16:34.781Z] node-puppeteer         | > puppeteer@1.18.1 install /app/node_modules/puppeteer
[2019-07-18T10:16:34.781Z] node-puppeteer         | > node install.js
[2019-07-18T10:16:34.781Z] node-puppeteer         | 
[2019-07-18T10:16:34.781Z] node-puppeteer         | ERROR: Failed to download Chromium r672088! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
[2019-07-18T10:16:34.781Z] node-puppeteer         | Error: end of central directory record signature not …
```
=> ci(jenkins): retry in case some enviromental issues

packages/rum-react/package.json, packages/rum-react/src/get-apm-route.js, packages/rum-react/src/get-with-transaction.js, packages/rum-react/test/e2e/with-router/switch.e2e-spec.js
+ fixes #344 
In react, there are two recommended ways to instantiate network requests inside components
- in componentDidMount lifecycle which happens before rendering the component
- useEffect hook which is supported in react > 16.7.x versions
Since we are wrapping the underlying component that renders the route, We have to account for any network effects that happens inside these two methods to capture those requests as spans in the route-change transaction. 
By registering to the cDM of class based component we are not able to create spans for fetch/XHR happening inside effect callbacks. 
React internally uses scheduler (based on MessageChannel) and `requestAnimationFrameWithTimeout` logic to run the effects registered inside useEffect callbacks which is scheduled to run after the …
=> fix(rum-react): capture network requests inside useEffect hook

CONTRIBUTING.md, dev-utils/karma.js, dev-utils/test-config.js, package-lock.json, package.json, packages/rum-core/karma.bench.conf.js, packages/rum-core/karma.conf.js, packages/rum-core/package.json, packages/rum-core/test/benchmarks/performance-monitoring.bench.js, packages/rum-core/test/common/apm-server.spec.js, packages/rum-core/test/error-logging/error-logging.spec.js, packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js, packages/rum-react/karma.conf.js, packages/rum-react/package.json, packages/rum/karma.conf.js, packages/rum/package.json, packages/rum/test/e2e/index.js, packages/rum/test/e2e/standalone-html/opentracing.js, packages/rum/test/integration/index.spec.js, packages/rum/test/specs/index.spec.js
+ part of elastic/apm-agent-rum-js#308 
+ refactor karma config based on the babel/webpack configs. 
+ move global config in single place. 
+ ability to watch files on dev with `npx lerna run tdd --scope=@elastic/<pkg-name>`
=> chore(karma): watch files in dev and run individual tests

packages/rum-core/src/common/patching/fetch-patch.js, packages/rum-core/src/common/patching/history-patch.js, packages/rum-core/src/common/patching/index.js, packages/rum-core/src/common/patching/xhr-patch.js, packages/rum-core/src/performance-monitoring/performance-monitoring.js, packages/rum/src/apm-base.js
+ patching logic check should be implemented by the consumer and we have a global patchAll function which takes care of doing the patching for AJAX,  FETCH and History state change only once.
=> chore(rum-core): remove duplicate patch boolean logic

packages/rum-core/src/performance-monitoring/performance-monitoring.js, packages/rum-core/test/benchmarks/performance-monitoring.bench.js, packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
+ remove unused `sendTransactions` which is used only in benchmarks. saves bundle size.
=> refactor(rum-core): remove test specific code from perf-monitoring

package-lock.json, packages/rum-core/NOTICE.txt, packages/rum-core/package.json, packages/rum/NOTICE.txt
+ Not sure how we missed it, but `stack-generator` is not used in rum-core.
=> chore(rum-core): remove unused stack-generator from deps

package.json
+ Previous releases `@elastic/apm-rum@4.3.0` and `@elastic/apm-rum@4.3.1` has `env.js` file published as part of the apm-rum package which is not intended to be published. Not sure how it got in, But this PR helps us prevent these issue in future. 
Check here - https://unpkg.com/browse/@elastic/apm-rum@4.3.0/dist/lib/
=> chore(release): clean dist folder before preparing release

CHANGELOG.md, README.md, docs/index.asciidoc, package.json, packages/rum-core/README.md, packages/rum-react/README.md, packages/rum-react/package.json, packages/rum/README.md
Replaces `js-base` with `rum-js` in the documentation. Not sure if you wanted me to do this or not (as there are more instances of `js-base` in the codebase). You can close this if you want to tackle all changes in one PR.
For https://github.com/elastic/apm-agent-rum-js/issues/108.
=> [docs] Remove js-base from documentation

packages/rum/test/benchmarks/analyzer.js, packages/rum/test/benchmarks/config.js, packages/rum/test/benchmarks/pages/head.ejs, packages/rum/test/benchmarks/pages/init.ejs, packages/rum/test/benchmarks/profiler.js, packages/rum/test/benchmarks/run.js, packages/rum/test/benchmarks/server.js
Parse and excution time measurement is calculated in such a way that network overhead will not affect the parse and exec time. Plus random bytes are added to the bundle js content to avoid chrome caching the parsed/JIT'ed script. 
+ Add measurement for parse and execution time of apm bundle. 
+ Add metrics for bundle size for both minified and gzipped version. 
+ Add common metrics to the `parameters` list. 
Results
```js
{
"scenario": "basic",
"parameters.browser": "HeadlessChrome/77.0.3844.0",
"parameters.url": "http://localhost:9000/basic",
"parameters.runs": 3,
"bundle-size.minified.bytes": 50466,
"bundle-size.gzip.bytes": 15928,
"page-load-time.mean.ms": 20.313333331917722,
"page-load-time.p90.ms": 29.920000000856817,
"rum-init-time.mean.ms": 2.4733333460365734, …
```
=> chore(benchmark): add parse and exec time metrics to benchmark

docs/intro.asciidoc
The RUM Agent links to literal anchors in the APM Server documentation. These links will break on the switch from asciidoc to asciidoctor. This PR fixes the link to use new anchor tags added in https://github.com/elastic/apm-server/pull/2603.
Backports https://github.com/elastic/apm-agent-rum-js/pull/387.
For https://github.com/elastic/apm-server/issues/1965. Full error log available in https://github.com/elastic/docs/pull/1083#issuecomment-523130974.
=> [docs][4.x] Update link to APM server 

docs/intro.asciidoc
The RUM Agent links to literal anchors in the APM Server documentation. These links will break on the switch from asciidoc to asciidoctor. This PR fixes the link to use new anchor tags added in https://github.com/elastic/apm-server/pull/2603.
Backport to `4.x`.
For https://github.com/elastic/apm-server/issues/1965. Full error log available in https://github.com/elastic/docs/pull/1083#issuecomment-523130974.
=> [docs] Update link to APM server

packages/rum/src/bootstrap.js, packages/rum/test/node/index-export.spec.js, packages/rum/test/node/opentracing-export.spec.js, packages/rum/test/specs/index.spec.js
+ fixes elastic/apm-agent-rum-js#363
=> fix(rum): log unsupported message only on browser environment

packages/rum/package.json
+ benchmark run needs our bundle before starting the benchmarks. It was failing in our Jenkins run. 
```
@elastic/apm-rum: > @elastic/apm-rum@4.4.2 bench /app/packages/rum
@elastic/apm-rum: > node test/benchmarks/run.js
@elastic/apm-rum: fs.js:646
@elastic/apm-rum:   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
@elastic/apm-rum:                  ^
@elastic/apm-rum: Error: ENOENT: no such file or directory, open '/app/packages/rum/dist/bundles/elastic-apm-rum.umd.min.js'
@elastic/apm-rum:     at Object.fs.openSync (fs.js:646:18)
@elastic/apm-rum:     at fs.readFileSync (fs.js:551:33)
@elastic/apm-rum:     at getMinifiedApmBundle (/app/packages/rum/test/benchmarks/analyzer.js:36:10)
@elastic/apm-rum:     at Object.<anonymous> …
```
=> chore(benchmarks): build bundles before running benchmarks [skip ci]

Jenkinsfile
- GIT_SHA contains the git merge commit therefore it does not exist in the upstream repo.
- GIT_BASE_COMMIT contains the git commit from the upstream repo.
=> ci(jenkins): Fix environment variable used to calculate git commit

packages/rum-react/src/get-with-transaction.js, packages/rum-react/test/specs/get-apm-route.spec.js, packages/rum-react/test/specs/get-with-transaction.spec.js
+ fixes elastic/apm-agent-rum-js#386 
+ blocks the kibana integration with RUM.
=> fix(rum-react): respect active flag in react integration

.travis.yml, dev-utils/build.js, dev-utils/webdriver.js, packages/rum-react/test/e2e/with-router/general.e2e-spec.js, packages/rum-react/test/e2e/with-router/switch.e2e-spec.js, packages/rum-react/test/e2e/with-router/webpack.config.js
+ fix elastic/apm-agent-rum-js#400 
+ Increase the timeout for script execution commands to 30 seconds. 
+ handle issues with setTimeout not being supported on Firefox and MSEdge
+ Due to the bundles getting generated for React in dev mode, the size of the bundles are huge and it causes E2E tests to fail in some browsers. 
+ By compiling the bundles in prod mode, the size of the bundles gets reduced from 1.6 MB to ~300Kbs. This should reduce the time required for downloading the script which is 30 seconds by default. 
+ Run react test only on 7.0.0 stack
=> chore(saucelabs): fix script timeout issues in saucelabs

packages/rum-angular/package.json
+ During the last release 4.4.3, angular package alone was not published. Since the cli considered it as private package due to the absence of access field set as `public`.
=> chore(rum-angular): fix npm publish config in angular package [skip ci]

.travis.yml
+ Our Jenkins pipeline already runs all of the packages/* tests in multiple stack versions. We can remove the run the sauce tests through travis on single stack to reduce the wait times and timeouts in travis.
=> chore(travis): run packages tests only on single stack

packages/rum-core/src/error-logging/error-logging.js, packages/rum-core/test/error-logging/error-logging.spec.js
+ fixes https://github.com/elastic/apm-agent-rum-js/issues/416
+ When script error is thrown, error key is set to `null` which passes the typeof `object` check. We handle this case in this PR and the code portions are merged to make it cleaner.
=> fix(rum-core): handle script error events properly

packages/rum-react/src/get-with-transaction.js, packages/rum-react/test/specs/get-with-transaction.spec.js
+ fixes elastic/apm-agent-rum-js#410 
+ We need to create route change transaction only when component mounts(first render in terms of effect terminology), however the effect hook was running on component rerenders. By passing empty arr on the useEffect hook, we create the transaction only on mount
+ We also need to create transaction only once inside setState and not inside function body since it gets executed on every render and effectively changes the transaction state which was passed down to the underlying component. 
This PR keeps the functional components in sync with the Class based ones. 
+ [x] Add tests
+ [x] figure out issues with transaction type not set to `route-change` in e2e. 
+ [x] Validate the issue with Kibana App
=> fix(rum-core): create transaction only on component mount

docs/sourcemap.asciidoc
For https://github.com/elastic/apm-server/pull/2728. Must be merged at the same time.
=> [2.x] docs: update moved secret token link

docs/sourcemap.asciidoc
For https://github.com/elastic/apm-server/pull/2728. Must be merged at the same time.
=> [3.x] docs: update moved secret token link

docs/sourcemap.asciidoc
For https://github.com/elastic/apm-server/pull/2728. Must be merged at the same time.
=> [4.x] docs: update moved secret token link

dev-utils/dep-info.js, packages/rum-react/NOTICE.txt
+ The previous version of gen-notice script does not take mono repo in to account and it fails to generate Notice.txt for all packages. 
+ Refactored the script to account for package dependency graph and calculate the score of the packages based on how they are used. So right now the score would look like 
```js
{
"rum-core": 0,  // does not depend on any internal packages
"rum": 1, // depends on rum core
"rum-react": 2 // depends on rum which internally depends on rum-core
}
```
We need to sort them since the notice generation for packages would start from the one with least score. 
+ Also account for node_modules hoisting and figure out the license/notices inside root node_modules in addition to package/node_modules level.
=> chore(notice): generate notice based on dependency graph

dev-utils/webdriver.js, packages/rum-core/src/common/constants.js, packages/rum-core/src/performance-monitoring/capture-navigation.js, packages/rum-core/src/performance-monitoring/performance-monitoring.js, packages/rum-core/src/performance-monitoring/transaction-service.js, packages/rum-core/src/performance-monitoring/transaction.js, packages/rum-core/test/fixtures/user-timing-entries.js, packages/rum-core/test/performance-monitoring/capture-navigation.spec.js, packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js, packages/rum-core/test/performance-monitoring/transaction-service.spec.js, packages/rum-react/test/e2e/components/manual-component.js, packages/rum-react/test/e2e/with-router/general.e2e-spec.js, packages/rum-react/test/e2e/with-router/general.js, packages/rum-react/test/e2e/with-router/webpack.config.js
+ fixes elastic/apm-agent-rum-js#268 
+ Use transaction start time as a filtering logic for capturing resource and user timing spans inside transaction timeframe. 
Should be merged after elastic/apm-agent-rum-js#424 
+ [x] Update Unit tests
+ [x] Add E2E tests
=> feat(rum-core): capture resource and user timing spans for soft navigation

codecov.yml
This PR disables the path report mode and uses the parent commit as a reference to calculate the coverage report.
closes #417
=> fix: change codecov report setting

scripts/build_docs.sh
Closes https://github.com/elastic/apm-agent-rum-js/issues/243.
Build the docs with:
`npm run build-docs` – Builds the docs
`PREVIEW=1 npm run build-docs` – Builds the docs and opens a local preview
---
It might make more sense to add `PREVIEW=1` here so that the docs open by default?
https://github.com/elastic/apm-agent-rum-js/blob/e9938243a657405d2f231be93d258274fc4e5cc5/package.json#L16
=> [docs] Fix build script

packages/rum-core/src/common/url.js, packages/rum-core/test/common/url.spec.js
+ fixes elastic/apm-agent-rum-js#444 
+ Handle the pathname resolution according to browser URL implementation. 
+ Added more tests to cover this case.
=> fix(rum-core): handle relative urls without slash properly

docs/angular-integration.asciidoc, packages/rum-angular/src/apm-service.ts, packages/rum-angular/test/e2e/with-router/app/app.module.ts
+ fixes elastic/apm-agent-rum-js#437 
+ Libraries needs to use explicit injection to make it work with all build configs.
+ Since the injection uses Reflection API like metadata and decorate, its better to use explicit check instead of doing `instanceof` since it fails with Angular CLI builds. 
+ remove the activated route deps since we can extract the firstChild from router state.  
+ Modify the E2E tests with the new behaviour. 
+ Update the angular docs to reflect the same. 
We can extend the tests in the future to include Angular AOT compiler and all those, but it requires pulling in lots of dependencies, so kept it simple for now and tested all the scenarios in the example repo which is a repo constructed with Angular CLI https://github.com/railsstudent/apm-rum-angular-routing-failed
=> fix(rum-angular): use explicit angular injection for service

docs/agent-api.asciidoc, packages/rum-core/src/common/config-service.js, packages/rum-core/test/common/config-service.spec.js, packages/rum-core/test/error-logging/error-logging.spec.js, packages/rum-core/test/performance-monitoring/transaction-service.spec.js
+ fixes #448 
+ Removed `configService.set` since the functionality is not required and we can achieve the same using `setConfig`.
+ Removed config.active settings in test since the agent is `active` by default.
=> fix(rum-core): ensure context metadata is shallow merged on transaction

Jenkinsfile
- Let's reuse the top-level agent to reduce the number of fo requested agents and speed up just a bit the builds.
- Reset labels to be `linux && immutable` to help with what kind of OS is required to be used.
=> ci(jenkins): reuse agents (2 less agents to be used)

.ci/scripts/benchmarks.sh, .ci/scripts/test.sh, Jenkinsfile, dev-utils/docker-compose.yml, package.json, packages/rum-core/test/benchmarks/performance-monitoring.bench.js, scripts/benchmarks.js
- When should match regex for tags.
- Cleanup the workspace after the execution, _ALWAYS_
- Required to pass the user to map the docker container user correctly.
=> ci(jenkins): benchmark in a bare metal

packages/rum-core/src/common/apm-server.js, packages/rum-core/src/common/utils.js, packages/rum-core/src/performance-monitoring/breakdown.js, packages/rum-core/src/performance-monitoring/performance-monitoring.js, packages/rum-core/src/performance-monitoring/span-base.js, packages/rum-core/src/performance-monitoring/transaction-service.js, packages/rum-core/src/performance-monitoring/transaction.js, packages/rum-core/test/performance-monitoring/breakdown.spec.js, packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js, packages/rum-core/test/performance-monitoring/transaction-service.spec.js, packages/rum-core/test/performance-monitoring/transaction.spec.js
+ Introduce setting `start` and `end` of transaction and spans through options arguments
+ Also address these comments  https://github.com/elastic/apm-agent-rum-js/issues/289#issuecomment-534999842
TODO
+ [x] The algorithm needs few changes and tests fails currently at the moment.
=> feat(rum-core): move breakdown algorithm post transaction finish

dev-utils/test-servers.js, packages/rum-core/src/common/apm-server.js, packages/rum-core/src/common/config-service.js, packages/rum-core/src/common/constants.js, packages/rum-core/test/common/apm-server.spec.js, packages/rum-core/test/common/config-service.spec.js, packages/rum/test/specs/apm-base.spec.js
Part of elastic/apm-agent-rum-js#253
store remote config in localStorage
=> feat(rum-core): use etag for fetching config

packages/rum-core/src/performance-monitoring/breakdown.js, packages/rum-core/test/fixtures/navigation-entries.js, packages/rum-core/test/performance-monitoring/breakdown.spec.js, packages/rum-core/test/performance-monitoring/capture-navigation.spec.js
+ part of elastic/apm-agent-rum-js#289 
+ To be able to drill down in to network more and also make the explanation easier for the users since it closely matches the navigation timing spec.
=> feat(rum-core): align breakdown types based on navigation timing

packages/rum-core/src/common/apm-server.js, packages/rum-core/test/common/apm-server.spec.js
+ fix elastic/apm-agent-rum-js#289
=> refactor(rum-core): remove optional timestamp from breakdown metrics

docs/framework-integrations.asciidoc
+ Missed it while doing the Vue docs elastic/apm-agent-rum-js#465
=> docs: add vue integration link in framework docs [skip ci]

dev-utils/build.js
+ fix https://github.com/elastic/apm-agent-rum-js/issues/482
+ By default webpack uses `browser`, `main` and `module`. Since we expose source as a field in our internal packages, we can use it to resolve to the current source changes which can be reflected easily in karma watch and webpack watch modes.
=> chore: build must watch for local packages while testing

docs/react-integration.asciidoc
+ document a solution for elastic/apm-agent-rum-js#487 since there is no easy way to auto instrument the lazy rendered components currently.
=> docs(rum-react): lazy rendered routes instrumentation [skip ci]

packages/rum-core/src/common/patching/fetch-patch.js, packages/rum-core/src/common/patching/xhr-patch.js, packages/rum-core/test/common/xhr-patch.spec.js
+ fix elastic/apm-agent-rum-js#486 
+ Small optimisation to ignore task creation process / event listener registration for the ignored XHR  objects (APM Server Request)
+ Also cleaned up the task object since some fields were not required to be passed around.
=> perf(rum-core): ignored XHR's are exempted from task creation process

CHANGELOG.asciidoc
As discussed on slack, this adds a placeholder `changelog.asciidoc` file so that your next release doesn't blow up the doc build.
For https://github.com/elastic/apm-agent-rum-js/issues/511.
=> [4.x][docs] Add placeholder changelog.asciidoc

packages/rum-core/src/common/context.js, packages/rum-core/src/common/patching/fetch-patch.js, packages/rum-core/src/common/url.js, packages/rum-core/src/performance-monitoring/capture-navigation.js, packages/rum-core/src/performance-monitoring/performance-monitoring.js, packages/rum-core/src/performance-monitoring/span-base.js, packages/rum-core/src/performance-monitoring/span.js, packages/rum-core/src/performance-monitoring/transaction-service.js, packages/rum-core/src/performance-monitoring/transaction.js, packages/rum-core/test/common/apm-server.spec.js, packages/rum-core/test/common/context.spec.js, packages/rum-core/test/common/url.spec.js, packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js, packages/rum-core/test/performance-monitoring/transaction.spec.js
+ relates elastic/apm-agent-rum-js#490 elastic/apm-agent-rum-js#513 
+ Add the necessary `span.desination.*` fields for all outgoing spans to help with service maps and siem intergration
+ This PR changes the overall context addition which happens across multiple place and unifies them in a single place to ease the development and addition of new fields on context easier. 
+ Custom URL parser is enhanced with more fields `port` and `hostname` to make the destinations fields addition easier. 
+ Context addition happens on span end and transaction end instead of doing it during the middle of the transaction and span creation process. 
+ [x] Fix parsing of hostname for `http://[::1]:8080/`
+ [x] Add tests for context
+ [x] Add tests for URL parsing of port and hostname
=> feat(rum-core): enrich span context with desination metadata

packages/rum-core/src/common/truncate.js, packages/rum-core/test/common/truncate.spec.js, packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
+ fix elastic/apm-agent-rum-js#490
+ Tested manually with the latest APM-server master.
=> chore(rum-core): tests for sending span destination context to server

packages/rum-core/karma.conf.js, packages/rum-core/test/common/url.spec.js
+ fix elastic/apm-agent-rum-js#534 
+ Added incompatible tests in separate level to identify if we can align with spec closer in future.
=> chore(rum-core): add native URL parser tests aganist polyfill

packages/rum-vue/src/index.js
Not all projects will use router, but the plugin currently assumes router is always provided.
=> feat(rum-vue): only hook router if provided

dev-utils/webdriver.js, package-lock.json, package.json
+ fix #176 
+ Uses the new `devtools` package to run both chrome and firefox on headless mode to run E2E tests.
When the mode is set to `none` which is on local, we run it by default on Headless and when set to `saucelabs`,we run it on all configured test browsers.
=> chore: run e2e tests locally on chrome & firefox headless

packages/rum/test/benchmarks/profiler.js
+ Since the disk cache was shared between runs, the results for `basic` and `heavy` scenarios were varying by a small margin which is not the case. Now, we run the benchmark on a incognito browser context which does not share cache for each session. Makes the results predictable.
=> chore(benchmark): get predictable results on each run

packages/rum/src/index.d.ts, packages/rum/test/types/index.spec.ts
+ Hope this the last , figured out this from this test file https://github.com/elastic/apm-agent-rum-js/blob/master/packages/rum-angular/test/index.ts. 
+ Also matched the exported members with the one from JS to keep it clear. 
We dont use `apmBase` directly on most test so it was hard to figure out this case.
=> chore: apmbase export types must reflect constructor properties

CHANGELOG.asciidoc, package.json, scripts/build_docs.sh
While trying to replicate the bug found in https://github.com/elastic/apm-agent-rum-js/issues/570, I found a different bug with the doc build script. This PR does three things:
1. Updates two broken links in `CHANGELOG.asciidoc`. Looks like my regex wasn't quite good enough when I was changing the changelog from md to asciidoc. On a related note, why does the same release message appear for 2.2, 2.2.1, and 3.0? `* introduce subtype and action in Spans {commit}5fd4af7[5fd4af7] {pull}9[#9]`. This existed in the old md file: https://github.com/elastic/apm-agent-js-core/blob/master/CHANGELOG.md.
2. Removes the `--direct-html` flag as it is now the default option.
3. Opens the documentation by default when running `npm run build-docs`. I don't know of a use case where you wouldn't want this to …
=> [docs] fix broken doc build script

docs/vue-integration.asciidoc, packages/rum-vue/src/error-handler.js, packages/rum-vue/src/index.js, packages/rum-vue/test/specs/error-handler.spec.js
+ fix elastic/apm-agent-rum-js#555 
+ Send extra information available from Vue instance and add it to the error context. This includes
- `component` - component responsible for the error. `anonymous` if name is not set. 
- `lifecycleHook` on where the error occurred
- `file` pointing to the actual component file `<component>.vue`
TODO
+ [x] Add tests
+ [x] Update docs
=> feat(rum-vue): capture errors in vue app automatically

packages/rum-core/src/performance-monitoring/transaction-service.js, packages/rum-core/test/performance-monitoring/transaction-service.spec.js
+  fix elastic/apm-agent-rum-js#583 
+ Transaction `onStart` hook should be called only once when the transaction is reused during the lifetime of a transaction.
=> fix(rum-core): avoid firing transaction-start event on reused transactions

packages/rum-vue/package.json
+ fix elastic/apm-agent-rum-js#574 
+ Vue plugin does not depend on Vue router and can work without router option being provided.
=> chore(rum-vue): remove vue-router from peer dependencies

packages/rum-core/src/performance-monitoring/transaction-service.js, packages/rum-core/test/performance-monitoring/transaction-service.spec.js
=> fix(rum-core): do not capture timing spans for unsampled transactions

dev-utils/integration-test.js
it evaluates an environment variable to enable or disable the certificates validation.
It allows using self-signed certificates for ITs.
related to https://github.com/elastic/apm-integration-testing/issues/13 and https://github.com/elastic/apm-integration-testing/issues/221
=> test: allow to disable certificates verification on ITs

packages/rum-core/src/common/constants.js, packages/rum-core/src/common/patching/event-target-patch.js, packages/rum-core/test/common/event-target-patch.spec.js, packages/rum-core/test/error-logging/error-logging.spec.js, packages/rum-core/test/index.js
part of #496 
This PR adds patching for EventTarget. It doesn't not register any event listeners for the EventTarget patch events, will do that in a separate PR.
=> feat(rum-core): add EventTarget patch

packages/rum-core/src/common/constants.js, packages/rum-core/src/common/context.js, packages/rum-core/src/common/utils.js, packages/rum-core/src/performance-monitoring/breakdown.js, packages/rum-core/src/performance-monitoring/capture-navigation.js, packages/rum-core/src/performance-monitoring/perf-entry-recorder.js, packages/rum-core/src/performance-monitoring/performance-monitoring.js, packages/rum-core/src/performance-monitoring/transaction-service.js, packages/rum-core/test/common/utils.spec.js, packages/rum-core/test/fixtures/lcp-entries.js, packages/rum-core/test/fixtures/longtask-entries.js, packages/rum-core/test/performance-monitoring/perf-entry-recorder.spec.js, packages/rum-core/test/performance-monitoring/transaction-service.spec.js, packages/rum-core/test/utils/globals-mock.js, packages/rum-vue/test/e2e/webpack.config.js
+ part of elastic/apm-agent-rum-js#478 
+ fix #376 
+ Introduces **Performance Observer** to capture `Longtask` and `Largest contentful paint` during transaction lifetime. 
+ LCP is added as a mark whereas `Longtasks` are created as spans to associate them in the breakdowns which provides a overview of how much time it spent on doing long tasks.
=> feat(rum-core): capture long tasks and lcp using performance observer

docs/advanced-topics.asciidoc
+ part of elastic/apm-agent-rum-js#478 
+ Added config for monitoring longtasks `monitorLongtasks` which is set to true by default. 
+ Added doc on how to interpret these tasks in the UI.
=> docs: interpreting longtasks as spans

.ci/scripts/pull_and_build.sh, .ci/scripts/test.sh
Reduces the verbose output that's generated when pulling and building the docker images for the test stage.
This will help to debug console log outputs in the CI
I did test this with a mock error in the Dockerfile ( `RUN exit 1` ) and the outcome was something like the below snippet
```
+ docker-compose -f ./dev-utils/docker-compose.yml --log-level INFO build --quiet --force-rm
WARNING: The STACK_VERSION variable is not set. Defaulting to a blank string.
WARNING: The SCOPE variable is not set. Defaulting to a blank string.
WARNING: The APM_SERVER_URL variable is not set. Defaulting to a blank string.
WARNING: The BUILD_NUMBER variable is not set. Defaulting to a blank string.
WARNING: The BRANCH_NAME variable is not set. Defaulting to a blank string.
WARNING: The JENKINS_URL variable is …
```
=> ci(jenkins): less verbose console output

docs/configuration.asciidoc, packages/rum-core/src/common/config-service.js, packages/rum-core/src/performance-monitoring/transaction-service.js, packages/rum-core/test/performance-monitoring/transaction-service.spec.js
+ part of elastic/apm-agent-rum-js#478 
+ Adds a config option to monitor longtasks as part of all managed transaction
+ The config is set to `false` by default for now. I am trying to understand the performance impact of capturing longtasks and PerformanceObserver in general. will set it to true once I find some details. Right now we use a single PO at the start, but I am not sure if its the correct approach as the spec does not talk about reusability and also if we observer/disconnect using same observer, observing on entry types multiples times triggers warnings. We are still able to measure longtaks, but its safer now to disable it till we learn more.  #601
=> feat(rum-core): add config option to monitor longtasks

dev-utils/webdriver.js, packages/rum-core/src/common/constants.js, packages/rum-core/src/common/instrument.js, packages/rum-core/src/performance-monitoring/performance-monitoring.js, packages/rum-core/src/performance-monitoring/transaction.js, packages/rum-core/test/common/instrument.spec.js, packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js, packages/rum-core/test/performance-monitoring/transaction.spec.js, packages/rum/test/e2e/general-usecase/app.e2e-spec.js, packages/rum/test/e2e/general-usecase/app.js, packages/rum/test/e2e/general-usecase/index.html
Part of #496 
This PR captures click events as `user-interaction` transactions.
=> feat: capture click user-interaction transactions

package-lock.json, package.json, packages/rum-core/karma.bench.conf.js, packages/rum/test/benchmarks/analyzer.js, packages/rum/test/benchmarks/config.js, packages/rum/test/benchmarks/profiler.js, packages/rum/test/benchmarks/run.js, scripts/benchmarks.js
+ Just playing around and understanding how our agent performs in different browsers. 
+ uses the https://github.com/microsoft/playwright to run the benchmarks instead of puppeteer. 
+ Puppeteer now also released v2.1.0 which supports launching firefox. https://github.com/puppeteer/puppeteer/releases/tag/v2.1.0
=> chore(benchmark): run benchmarks on chromium, firefox and webkit

docs/sourcemap.asciidoc
The release build isn't having a fun day. This fixes one of the broken links. I'm sorry, but I need to backport this to `4.x`, `3.x`, and `2.x`.
The API Key documentation moved around some of the secret token documentation, which is why this problem is occurring. I'll also open an issue to update the documentation to add API key information later.
Context: https://elasticsearch-ci.elastic.co/job/elastic+docs+master+build/12089/console
=> docs: Fix release build

packages/rum-core/src/common/apm-server.js, packages/rum-core/test/common/apm-server.spec.js
This bug was introduced around 4.0.2 release and therefore affects nearly all 4.x versions. I've added more tests to cover this case. I've also removed the undocumented `service` property from the payload passed to filters.
=> fix: pass correct properties to payload filters

packages/rum-core/src/common/patching/event-target-patch.js, packages/rum-core/test/common/event-target-patch.spec.js
This PR makes sure that we only capture events on instances of Element. Furthermore, some frameworks like turbolinks patch `addEventListener` and this might cause the target to be undefined, checking the instance of the target will prevent this as well.
=> fix(rum-core): Only capture events on Elements

Jenkinsfile
- Run APM-ITs after running the tests.
- Run Coverage at the very end
The `Integration Tests` stage cannot be easily triggered in parallel with the `Test` stage. So there were two options, either run the ITs firstly and then the Test stage or the other way around. As agreed we will run after the `Test` stage.
Closes https://github.com/elastic/apm-agent-rum-js/issues/640
=> ci(jenkins): test pipeline optimisation

.github/workflows/bundle-size.yml, .github/workflows/main.yml
+ trying out the compressed size plugin to know size per file. 
https://github.com/marketplace/actions/compressed-size-action
Might delete it if its not super useful for us.
=> chore(bundlesize): add github workflows to check compressed size

Jenkinsfile
Enable the benchmark without sending the data to ES for the pull requests that change any of the files that are directly related to the benchmark.
This will help to automatically validate any changes that could affect the benchmark implementation before merging to master.
=> ci(jenkins): enable benchmark for PRs if changes in the benchmark files

Jenkinsfile
Let's disable the benchmark execution for the time being since the benchmark stage fails and gets stalled until the 3 hours timeout happens.
https://github.com/elastic/apm-agent-rum-js/pull/650 might rollback this PR.
=> ci(jenkins): benchmark fails with playwright in the CI

dev-utils/build.js, packages/rum-core/test/common/apm-server.spec.js, packages/rum-core/test/performance-monitoring/transaction-service.spec.js, packages/rum-core/test/performance-monitoring/transaction.spec.js
Part of #620 
This PR fixes some of the previously disabled tests and removes the rest which are unnecessary at this point. Going forward we should add comments to tests that we decided to disable about the reason for it and how/when we can fix and enabled the test.
This PR also fixes the source-map for tests. Note that `inline-source-map` seem to be the only way to get sourcemaps work with karma/jasmine.
=> chore(tests): fix/remove disabled tests

dev-utils/run-script.js
+ fix #649 
+ Overriding `uncaughtException` would result in exitCode resulting in 0 and consuming our test errors. 
+ process.exit(exitcode) is unnecessary as the process would be exited anyways when error happens. 
This PR would result in node tests being broken because of this issue #646.
=> chore(dev): fix uncaughtException handler from consuming test errors

packages/rum-core/src/common/constants.js, packages/rum-core/src/performance-monitoring/performance-monitoring.js, packages/rum/test/bundle/bundle.spec.js
+ hit us because of sideeffect of allowing failures on bundlesize
+ webpack warnings was not considered as blockers.
Added the fix in bundle tests that would error out on warnings as well and also used the default webpack config to make sure we align with release bundles.
=> fix(rum-core): export browser responsiveness interval correctly

dev-utils/run-script.js, package.json
When running locally `concurrency=1` is required since each of individual packages run their own servers and they conflict with each other if run in parallel. 
This doesn't effect the speed of tests running on CI since we always pass a single scope to each runner.
=> chore: fix test script for running locally

.ci/docker/node-puppeteer/Dockerfile, dev-utils/docker-compose.yml, packages/rum/test/benchmarks/config.js, packages/rum/test/benchmarks/run.js
+ extracting some commits from this #https://github.com/elastic/apm-agent-rum-js/pull/650
+ Playwright requires Node >8 otherwise we will see this error - https://github.com/microsoft/playwright/blob/master/docs/troubleshooting.md#referenceerror-url-is-not-defined
+ Firefox and Webkit require more packages to work correctly inside docker. Will be addressed in separate PR
=> chore(benchmark): run only on chromium and exit process

.ci/docker/node-playwright/Dockerfile, packages/rum/test/benchmarks/config.js, packages/rum/test/benchmarks/profiler.js
+ Fixing the webkit runs - webkit cannot understand `--no-sandbox` and results in parse error. so 
we have chromium/other browser specific launch options
+ fix nitpicks from other PR https://github.com/elastic/apm-agent-rum-js/pull/683
Benchmark working - https://apm-ci.elastic.co/job/apm-agent-rum/job/apm-agent-rum-mbp/job/PR-685/3/console
=> chore(benchmark): run profiler benchmark in webkit

packages/rum-core/src/performance-monitoring/capture-navigation.js, packages/rum-core/test/fixtures/paint-entries.js, packages/rum-core/test/performance-monitoring/capture-navigation.spec.js, packages/rum-core/test/utils/globals-mock.js
https://github.com/elastic/apm-agent-rum-js/issues/680
=> Fix(rum-core): Check if first-contentful-paint exists before setting the agent marks

packages/rum-core/src/common/apm-server.js, packages/rum-core/test/common/apm-server.spec.js
This PR changes the agent name to `rum-js`.
- Both APM UI and APM server already support both names on 7.x versions, however this is a breaking change for version 6.x 
Fixes #379
**Please don't merge yet.**
=> BREAKING CHANGE: change agent name to rum-js

dev-utils/test-servers.js, packages/rum-core/src/common/config-service.js
Part of #477
This PR uses the official W3C tracecontext `traceparent` header instead `elastic-apm-traceparent` which we previously used.
=> BREAKING CHANGE: use the official traceparent header

docs/configuration.asciidoc, packages/rum-core/src/common/config-service.js, packages/rum-core/test/performance-monitoring/transaction-service.spec.js
=> feat(rum-core): monitor longtasks by default during active transaction

docs/configuration.asciidoc, docs/distributed-tracing-guide.asciidoc
Part of #477
* add backend agents matrix
=> docs: document W3C tracecontext header

docs/agent-api.asciidoc, docs/span-api.asciidoc, docs/transaction-api.asciidoc
Part of #272 and #215 
* mention support fo boolean and number values for addLabels
=> docs: remove addTags method

packages/rum-core/src/common/utils.js, packages/rum-core/test/common/config-service.spec.js, packages/rum-core/test/common/utils.spec.js
=> BREAKING CHANGE: add support for boolean and number values in addLabels

docs/configuration.asciidoc, docs/distributed-tracing-guide.asciidoc, docs/upgrading.asciidoc
**What does this PR do?**
* Adds an upgrading guide for the APM RUM Agent version `5.x`.
* Removes documentation for the four removed config options
* Adds documentation for `eventsLimit`
**Related PRs**
* Closes https://github.com/elastic/apm-agent-rum-js/issues/671
* Related to https://github.com/elastic/apm-agent-rum-js/issues/501
**Screenshot of changes**
<details>
<summary>Click to expand!</summary>
</details>
=> [docs] Add upgrading to 5.x guide

packages/rum-core/src/common/patching/fetch-patch.js, packages/rum-core/src/performance-monitoring/performance-monitoring.js
=> feat(rum-core): set sync field only for synchronous spans

docs/release-notes.asciidoc
Adds a link to the 5.x release notes to make them easier to find.
=> docs: add link to 5.x release notes

docs/release-notes.asciidoc
I know we don't typically backport, but this seems like an important enough link to make an exception.
=> docs: add link to 5.x release notes (#711)

docs/distributed-tracing-guide.asciidoc
Please wait to merge until after https://github.com/elastic/apm-agent-dotnet/pull/771 has been merged.
The doc build will need to be retried with `@elasticmachine, run elasticsearch-ci/docs`.
=> docs: add link to dot net repo 

Jenkinsfile, docs/advanced-topics.asciidoc
- Any builds for any branch or PR that only contains changes related to the asciidoc then it will skip all the stages but the `checkout`
Docs validation happens with the `elasticsearch-ci/docs` therefore there is no need to validate anything in our end.
Closes https://github.com/elastic/apm-agent-rum-js/issues/715
=> ci(jenkins): speed up builds with only docs changes

scripts/lint-commits.sh
Solves
```
[2020-03-20T14:26:06.736Z] + commitlint --from=ce0db92d1ba057def0c81595340de4e9e59c4872~1
[2020-03-20T14:26:06.736Z] ⧗   input: perf(rum-core): random number generator using crypto.getRandomValues (#705)
[2020-03-20T14:26:06.736Z] 
[2020-03-20T14:26:06.736Z] * perf(rum-core): random number generator using crypto.getRandomValues
[2020-03-20T14:26:06.736Z] 
[2020-03-20T14:26:06.736Z] * chore: address review add tests
[2020-03-20T14:26:06.736Z] 
[2020-03-20T14:26:06.736Z] * chore: fix deps in package-lock
[2020-03-20T14:26:06.736Z] ✖   header must not be longer than 72 characters, current length is 75 [header-max-length]
```
See [master build](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fapm-agent-rum-mbp/detail/master/218/pipeline)
- Should the validation …
=> ci(jenkins): pull request title linting validation

packages/rum-core/test/benchmarks/index.js, packages/rum-core/test/benchmarks/performance-monitoring.bench.js
+ due to our recent breaking API change `sendTransactions` is renamed in to `sendEvents`. Reflecting the same in benchmarks as its broken right now
=> chore(benchmarks): use sendEvents for sending payload

packages/rum-core/src/performance-monitoring/capture-navigation.js, packages/rum-core/test/performance-monitoring/capture-navigation.spec.js
=> fix(rum-core): filter API calls from resource spans

packages/rum-core/src/common/utils.js
Fix for https://github.com/elastic/apm-agent-rum-js/issues/707
=> fix(rum-core): handle error when `performance` is not available

packages/rum-core/test/common/apm-server.spec.js
+ This currently breaks all our PR tests. 
+ Server recently landed a PR which changed the format of message, so had to account for that 
https://github.com/elastic/apm-server/pull/3594/files
=> chore(rum-core): fix apm-server error msg in test

dev-utils/build.js, packages/rum-angular/package.json
+ fixes #607 
+ Angular CLI builds the application using the target `es2015` as described in here https://angular.io/guide/deployment#differential-builds, which means our builds with `module` target wont work since we always transpile using the lowest version `IE 11`
+ There is a strong reason why we use `IE 11` as the least target since we do not want our users to transpile the dependencies code(If users are looking for more size wins, its better to follow this path as well) and instead make it work out of the box.  
+ With this PR, All webpack users would still be unaffected as it uses `module` target and can perform Tree shaking and rest like before. Angular CLI users would make use of the newly specified target `es2015` and can utilize the differential loading technique …
=> feat(rum-angular): support differential loading with CLI

Jenkinsfile
- Comparator was removed sometime ago
- Support markdown files too to skip the build
=> ci(jenkins): comparator is not needed

.ci/scripts/prepare-git-context.sh, Jenkinsfile, RELEASE.md, package-lock.json, package.json, scripts/prompt-release.js
Release automation from the master branch, with the below support:
- Email notification when a new release is triggered by the Jenkins UI.
- Input approval to confirm the release should be out with 12 hours waiting for.
- Release automation with 2FA.
- Update docs regarding the release process with the CI.
No hands!
Caused by https://github.com/elastic/apm-agent-rum-js/issues/518
- Input approval with the list of changes to be released
BO view:
Traditional view:
I just verified the production credentials worked as expected, for the repo https://github.com/v1v/test-2fa/commits/master I did run the pipeline
That released 1.4.0 (see the collaborators):
=> ci(jenkins): support release automation

.gitignore, package-lock.json, package.json, packages/rum/test/e2e/async-tests/app.js, packages/rum/test/e2e/async-tests/async.e2e-spec.js, packages/rum/test/e2e/async-tests/index.ejs, packages/rum/test/e2e/async-tests/webpack.config.js, packages/rum/test/e2e/bundle-test/index.html, packages/rum/test/e2e/general-usecase/index.html, packages/rum/test/e2e/manual-timing/index.html, packages/rum/test/e2e/utils.js
+ fix #191 
+ Adds async-tests which loads our agent bundle asynchronously and also added some explanation on not able to capture XHR/Fetch since we cant patch the API's later. This is an issue and we can rely on Resource Timing API's in these cases.
=> chore(rum): add standalone async loading tests

.ci/scripts/prepare-git-context.sh, Jenkinsfile, RELEASE.md, lerna.json
- Workspace is not anymore a shallow cloned but contains the whole history. Otherwise, the changelogs will not contain all the changes.
- Send email notification when the release has been published.
- Update RELEASE.md docs with more details.
- Enable verbose output when to publish and version. See [here](https://github.com/lerna/lerna/blob/5e790e5d661ee95e0dbc2160e6509e6691b8b9e3/core/project/README.md#command-specific-configuration)
=> ci(jenkins): release automation followups

packages/rum-react/src/get-apm-route.js, packages/rum-react/test/specs/get-apm-route.spec.js
+ Alternative solution to the #747 
+ This avoids the problem that would trigger full page reload when the query param is changed by any of the child components of `<ApmRoute>`
=> fix(rum-react): avoid rerendering on query param changes

docs/set-up.asciidoc, docs/upgrading.asciidoc, packages/rum/test/e2e/async-tests/index.ejs
+ As a result of #739 
+ Part of #191
+ Adds a blocking/non-blocking loading patter and also added some couple of caching header strategies users could use when hosting the bundle in the CDN.  
+ Also documented the caveat that DT might not work for calls that happened before the agent script is loaded.
=> docs: add blocking/nonblocking pattern on usage

CHANGELOG.asciidoc
Release - https://github.com/elastic/apm-agent-rum-js/releases/tag/%40elastic%2Fapm-rum%405.1.1
=> docs: add release notes for 5.1.1 [skip ci]

packages/rum-core/src/performance-monitoring/breakdown.js, packages/rum-core/src/performance-monitoring/capture-navigation.js, packages/rum-core/src/performance-monitoring/performance-monitoring.js, packages/rum-core/src/performance-monitoring/span.js, packages/rum-core/test/common/apm-server.spec.js, packages/rum-core/test/common/truncate.spec.js, packages/rum-core/test/performance-monitoring/breakdown.spec.js, packages/rum-core/test/performance-monitoring/span.spec.js
+ Unfortunately this bug has been around for sometime and I just found out when doing the RUM payload test for v3. 
+ I have added some tests to ensure we dont miss them in both payload and breakdown metricsets. 
Kibana APM UI can show the info correctly now
=> fix(rum-core): add subtype span info without camelCasing

docs/distributed-tracing-guide.asciidoc
Adds missing backend Agent distributed tracing links to the RUM distributed tracing guide.
Closes https://github.com/elastic/apm-agent-rum-js/issues/763.
=> docs: add missing distributed tracing setup links

docs/sourcemap.asciidoc
~NOTE: DO NOT MERGE YET. `elasticsearch-ci/docs` will fail until elastic/apm-server#3678 is merged.~ OK to merge now.
---
This PR simplifies the source map documentation in the RUM Reference. It moves the step by step content to the APM Server's "How-to guides" section, so we can have an end-to-end guide for applying source maps to error stack traces in one place.
For https://github.com/elastic/apm-server/issues/3564.
A component of https://github.com/elastic/apm-server/pull/3678.
=> docs: simplify source map docs

dev-utils/karma.js
+ Without this flag set to false, watch mode does not work correctly.
=> chore(dev): watch files when running karma dev

packages/rum-core/test/common/apm-server.spec.js
+ Our unit tests for the latest server snapshot started breaking because of the new changes in Server which disallows spans with negative duration https://github.com/elastic/apm-server/pull/3721. This PR fixes the span with correct duration.
=> chore(dev): fix span duration in tests

packages/rum-core/src/common/constants.js, packages/rum-core/src/performance-monitoring/breakdown.js, packages/rum-core/src/performance-monitoring/transaction-service.js, packages/rum-core/src/performance-monitoring/transaction.js, packages/rum-core/test/performance-monitoring/breakdown.spec.js, packages/rum-core/test/performance-monitoring/transaction-service.spec.js
+ fix #776 
+ Truncated spans are merged with the regular spans if it exists or they are treated as actual spans.
=> fix(rum-core): treat truncated spans as actual in breakdown

packages/rum-core/src/common/apm-server.js, packages/rum-core/src/common/compress.js, packages/rum-core/src/common/config-service.js, packages/rum-core/src/common/constants.js, packages/rum-core/src/common/context.js, packages/rum-core/src/common/utils.js, packages/rum-core/src/error-logging/error-logging.js, packages/rum-core/src/performance-monitoring/capture-navigation.js, packages/rum-core/src/performance-monitoring/perf-entry-recorder.js, packages/rum-core/src/performance-monitoring/performance-monitoring.js, packages/rum-core/test/common/apm-server.spec.js, packages/rum-core/test/common/compess.spec.js, packages/rum-core/test/common/compress.spec.js, packages/rum-core/test/index.js, packages/rum-core/test/performance-monitoring/perf-entry-recorder.spec.js, packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
+ fix #768 
+ Adds a new config option `compressPayload` which is set to false by default and when enabled will use the new v3 spec for reporting the events. 
+ Compression is done after the payload to make sure we don't break the existing version and also let the user supplied filters work as expected
+ floats are converted to integers and this would be applied for all the previous apm server versions as well and would be applied even if the flag is set to false. Server schema is a JSON number so this validation is intact. 
No of Spans 
+ 50 JS files
+ 3 Custom spans (Parsing document, DOM interactive etc)
+ Metricsets/Breakdown - 4 for page-load
| Name of the test               | Payload Size (approx bytes) |
| :------------------------ | :-------------------------: |
| Current Release …
=> perf(rum-core): compress server payload for all events

packages/rum-core/src/common/metrics.js, packages/rum-core/src/performance-monitoring/perf-entry-recorder.js, packages/rum-core/test/performance-monitoring/perf-entry-recorder.spec.js
+ fix #781 
+ Captures Total blocking time only for page-load navigations from long tasks.
+ Long tasks from only from same frame and same origins are added to the TBT as tasks from chrome extensions or plugins might end up influencing the TBT time and its not under the website owners/developer control. This is an extra precaution and we can also account for only `self` in future if child frames from ADS are also influencing this score.
=> feat(rum-core): capture total blocking time for navigation

packages/rum-core/src/common/config-service.js, packages/rum-core/test/common/config-service.spec.js, packages/rum-core/test/performance-monitoring/transaction-service.spec.js, packages/rum/test/specs/apm-base.spec.js
+ fix #780 
+ User configs would be merged with the actual config instead of having `defaults`. 
+ Added a test case and removed the `config.init` from places where unnecessary.
=> fix(rum): allow setting labels before initializing

packages/rum-core/src/bootstrap.js, packages/rum-core/src/common/bootstrap.js, packages/rum-core/src/common/polyfills.js, packages/rum-core/src/common/url.js, packages/rum-core/src/common/utils.js, packages/rum-core/src/index.js, packages/rum-core/test/bootstrap.spec.js, packages/rum-core/test/common/bootstrap.spec.js, packages/rum/src/apm-base.js, packages/rum/test/specs/index.spec.js
+ fixes #791 
+ Ensures the following when the agent script is loaded twice or agent script is used along with other framework integrations
-  `apm` instance is singleton 
- does not patch the `window.elasticApm` multiple times
- does not patch XHR, Fetch, History multiple times.
=> fix(rum): use single instance of apm across all packages

packages/rum-core/src/performance-monitoring/transaction-service.js, packages/rum-core/src/performance-monitoring/transaction.js, packages/rum-core/test/performance-monitoring/transaction-service.spec.js, packages/rum-react/test/e2e/with-router/general.e2e-spec.js, packages/rum/test/specs/apm-base.spec.js
+ fix #758 
+ User defined type for managed transaction should be considered a high priority as it would let users to filter these transactions in the UI in a better way. This applies only to managed transaction and custom transactions is not touched in this PR. 
+ Also moved and improved the logging after the redefining as it gives false information as mentioned in the linked issue.
=> fix(rum-core): consider user defined type of high precedence

CHANGELOG.asciidoc
+ release is https://github.com/elastic/apm-agent-rum-js/releases/tag/%40elastic%2Fapm-rum%405.2.0
=> docs: add release notes for 5.2.0

dev-utils/docker-compose.yml
workaround for https://github.com/elastic/beats/issues/18858
=> fix: workaround for elastic/beats#18858

dev-utils/docker-compose.yml
Env vars cannot be boolean in docker-compose files
```
[2020-06-01T09:56:29.359Z] services.apm-server.environment.BEAT_STRICT_PERMS contains false, which is an invalid type, it should be a string, number, or a null
```
=> fix: env var invalid type

Jenkinsfile
It archives the docker container details for every stage that runs docker.
- Go to the `artifact/docker-info` folder
- Look for the stage that you'd like to go deeper with
- Open the file `docker-containers.txt`
- Look for the container ID
- `<id>.log` is the logs for the container with `id`
- `<id>-cmd.txt` is the docker container run parameters
- `<id>-inspect.json` is the output of the docker inspect <id> command
(BO view)
Closes https://github.com/elastic/apm-agent-rum-js/issues/806
=> ci: use dockerLogs step

packages/rum-core/src/performance-monitoring/metrics.js, packages/rum-core/src/performance-monitoring/transaction-service.js, packages/rum-core/test/performance-monitoring/metrics.spec.js
+ fix #802 
+ On very long task entry, we populate the `module level metrics` constant and update the duration and use it once the page load is done to capture the TBT as spans. 
+ We have to do something similar for `CLS` as well.
=> fix(rum-core): capture tbt after all task entries are observed

packages/rum-core/src/performance-monitoring/metrics.js
+ shorter to use `startTime` as it fallbacks automatically to `renderTime` if its available or `loadTime`. 
+ More details - https://wicg.github.io/element-timing/#sec-performance-element-timing. LCP is part of element timing.
=> chore(rum-core): use startTime for LCP marks

Jenkinsfile
Create markdown file on the fly and populate the content as a GitHub comment. See https://github.com/elastic/apm-agent-rum-js/pull/826#issuecomment-650255846
Closes https://github.com/elastic/apm-agent-rum-js/issues/667
=> ci(jenkins): report bundlesize as a GitHub comment

packages/rum-core/src/common/context.js, packages/rum-core/src/performance-monitoring/capture-navigation.js, packages/rum-core/test/common/context.spec.js, packages/rum-core/test/performance-monitoring/capture-navigation.spec.js
+ fix #829 
+ This PR populates the destination information for span that is responsible for Initial HTML generation which comes under page-load transaction. So an example service request page from `www.example.com` would have a service map linked to `www.example.com` since the HTML fro the service is provided from that origin. This is in addition to other static resources like `JS, CSS, Images etc`. This would solve for both static and dynamically generated HTML's.
=> feat(rum-core): populate destination info for NT spans

packages/rum/src/index.d.ts
The apiVersion config option was added in 5.2.0 https://www.elastic.co/guide/en/apm/agent/rum-js/current/release-notes-5.x.html as part of this issue https://github.com/elastic/apm-agent-rum-js/issues/768.
However the option was not added to index.d.ts making it inaccessible when using typescript
=> add apiVersion config option to typescript

Jenkinsfile
The linting stage generates the bundlesize report that it will be used to compare on a PR basis. 
Otherwise, if using the docs filtering in the stage then the bundlesize report won't be generated and the PRs that got built when the latest build in the mastet branch got built with docs then they won't have anything to compare with.
This will avoid this particular corner case and apply bundlesize reports for every single commit with a build.
- https://github.com/elastic/apm-agent-rum-js/pull/838#issuecomment-655022184
=> ci: run linting always

docs/intro.asciidoc, docs/supported-technologies.asciidoc
+ fix #633 
+ part of #790 
+ Enhanced the feature section and also added user centric metrics section that has FCP, LCP, TBT, FID and longtasks that we have supported.
=> docs: add user centric metrics to supported list

docs/supported-technologies.asciidoc
+ fix #790  
+ Added more concept around how metrics are captured in the browser, Spec and other helpful links. Plus browser support. 
+ Helps with https://github.com/elastic/uptime/issues/234 
Preview - https://apm-agent-rum-js_846.docs-preview.app.elstc.co/guide/en/apm/agent/rum-js/master/supported-technologies.html
=> docs: enhance the user-centric metrics section

docs/troubleshooting.asciidoc
To assist support, we're adding disable instructions to each Agent's troubleshooting docs.
For https://github.com/elastic/observability-docs/issues/35.
=> docs: disable agent

packages/rum-core/src/common/compress.js, packages/rum-core/src/common/constants.js, packages/rum-core/src/common/utils.js, packages/rum-core/src/performance-monitoring/metrics.js, packages/rum-core/src/performance-monitoring/performance-monitoring.js, packages/rum-core/src/performance-monitoring/transaction-service.js, packages/rum-core/test/performance-monitoring/metrics.spec.js, packages/rum-core/test/performance-monitoring/transaction-service.spec.js
This PR adds CLS, FID and TBT to the ['experience' field](https://github.com/elastic/apm-server/issues/3972)
+ fix #795 
I think we should find a better place for storing metrics such as TBT and CLS.
Furthermore, we have too many places to store RUM specific data (page, marks, etc.) and I think we can take this opportunity to merge these together. I'm going to make a proposal for this on apm-server.
=> feat: add CLS, FID and TBT to experience field

packages/rum/package.json
This increases the bundle size for apm-rum and apm-opentracing. It should resolve errors seen here:
https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fapm-agent-rum-mbp/detail/master/308/pipeline/78/
=> chore(jenkins): increase bundlesize

packages/rum-core/src/common/logging-service.js, packages/rum-core/src/common/service-factory.js, packages/rum-core/test/common/logging-service.spec.js, packages/rum/src/apm-base.js, packages/rum/test/specs/apm-base.spec.js
+ fix #861 
+ The first logLevel update happens during the LoggingService creation phase in both active and also inactive phase.
+ The second logLevel update happens if users call `apm.config({})` or config is updated from remote config for the active phase.
=> fix(rum): use logLevel config when agent is inactive

packages/rum/src/opentracing.js, packages/rum/test/e2e/general-usecase/app.js
+ This is a bug that was captured while doing tests in failsafe browsers. 
+ On IE 10, we still create transactions from the OT tracer API which is not correct and should be a Noop. 
Blocks the other PR #866
=> fix(rum): use noop tracer on unsupported platforms

docs/custom-transactions.asciidoc, docs/transaction-api.asciidoc, packages/rum-core/src/common/utils.js, packages/rum-core/src/performance-monitoring/performance-monitoring.js, packages/rum-core/src/performance-monitoring/transaction-service.js, packages/rum-core/src/performance-monitoring/transaction.js, packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js, packages/rum-core/test/performance-monitoring/transaction-service.spec.js, packages/rum-core/test/performance-monitoring/transaction.spec.js, packages/rum/src/apm-base.js, packages/rum/test/e2e/standalone-html/opentracing.js
+ fixes #841 
+ Improves upon the work that is already on the original PR #194 
+ Adds an option `blocking` to the `startSpan` method that keeps the transaction open and allow controlling the behaviour of all managed transactions created by the agent itself through auto instrumentation or through user. 
+ Added `transaction.block(true)` method which can be used to control the closing of managed transactions. 
+ Added documentation on the custom transactions part with unmanaged and managed transactions.
=> feat(rum-core): provide api to block managed transactions 

packages/rum-core/src/common/constants.js, packages/rum-core/src/common/patching/xhr-patch.js, packages/rum-core/test/common/xhr-patch.spec.js, packages/rum-core/test/index.js, packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js, packages/rum/src/apm-base.js, packages/rum/test/specs/apm-base.spec.js
+ fix #871 
+ fix #864 
+ PR improves our XHR instrumentation code to account for abort, timeout and error states that happen in both the async and sync XHR implementations. Also it fixes the bug that causes the transaction to not get ended since we have not handled the cases before. 
- XHR being aborted
- XHR being timedout
- CORS error
- URL being down - Both Sync and Async
I have added tests for all cases to ensure they are covered. 
+ The timing information of the XHR would also be in sync with the resource timing Info as we don't schedule any macro task to for the auto instrumented XHR to get ended.
+ Confirmed with the Angular APP, this PR fixes the problem exposed in #864 as the macro task scheduling logic is gone and we correctly measure the real timings. 
+ We don't schedule …
=> fix(rum-core): capture xhr error states in transaction

docs/agent-api.asciidoc, docs/custom-transactions.asciidoc, docs/transaction-api.asciidoc, packages/rum/src/apm-base.js, packages/rum/test/specs/apm-base.spec.js
+ enhancement to #866 
+ Expose the same level of API as `transaction.startSpan` to the Agent API as both does the same job. Doing it here would make it easily discoverable to users.
=> feat(rum): allow creating blocking spans from agent api

CHANGELOG.asciidoc
+ For https://github.com/elastic/apm-agent-rum-js/releases/tag/%40elastic%2Fapm-rum%405.5.0
=> docs: release notes for 5.5.0

packages/rum-core/src/performance-monitoring/transaction-service.js, packages/rum-core/test/performance-monitoring/transaction-service.spec.js
+ `apm.startSpan` was creating options object even when there was an active transaction present which is wasteful to do in the first place. 
+ This PR improves the performance of `startSpan`method and skips options creation when there is already an active transaction.
=> perf(rum-core): avoid creating options when transaction exists

packages/rum-angular/src/apm-service.ts, packages/rum-core/src/common/config-service.js, packages/rum-react/src/get-with-transaction.js, packages/rum-react/test/specs/get-with-transaction.spec.js, packages/rum-vue/src/index.js, packages/rum/src/apm-base.js, packages/rum/test/specs/apm-base.spec.js
+ fix #881 
+ PR address the issue when the react ApmRoute component is used on the application and instrumentation should not happen when the RUM agent is not initialised. 
+ Added an `isActive` method on the APM agent which is used across all packages to check for three conditions
- is Platform supported
- Is the agent initialised
- Is the `active` config flag set to true
+ removed the isActive method from Config service to avoid confusion with the agent API.
=> fix(rum): do not instrument frameworks when agent is inactive

packages/rum/src/index.d.ts
Add typings for methods: `isActive`, `fetchCentralConfig`, `config`.
Since none of them has underscore at the beginning of their function names, I believed that they ought to be public methods, and should be typed.
=> feat(rum): add missing methods to types

packages/rum-core/src/common/apm-server.js
Added a default timeout to the `makeHttpRequest` method on apm-server
in the case, a payload or headers are passed to the function. Previously
the default timeout would only be applied if the third parameter was
not defined.
This will resolve the issue for https://github.com/elastic/apm-agent-rum-js/issues/896
=> fix(rum-core): add default timeout for xhr post requests

packages/rum-core/src/performance-monitoring/metrics.js, packages/rum-core/src/performance-monitoring/transaction-service.js, packages/rum-core/test/fixtures/fid-entries.js, packages/rum-core/test/performance-monitoring/metrics.spec.js, packages/rum-core/test/utils/globals-mock.js
+ fixes #898 
+ Also handles CLS values to be fixed with 3 decimals (Used in all core-vitals reports)
=> fix(rum-core): measure fid correctly for experience metric

packages/rum-core/src/performance-monitoring/capture-navigation.js, packages/rum-core/test/performance-monitoring/capture-navigation.spec.js, packages/rum-core/test/performance-monitoring/transaction-service.spec.js
+ fix #901 
+ I had a look at our data for past 30 days and confirmed this fix should make our CSM page account for all bugs. Also, the bug is applicable only to Safari users. 
+ Link to webkit issues - https://bugs.webkit.org/show_bug.cgi?id=186919, https://bugs.webkit.org/show_bug.cgi?id=168055
=> fix(rum-core): discard buggy navigation marks for page-load

Jenkinsfile, RELEASE.md
- Simplify the release process by filling only the required checkbox (`release`)
- Other input parameters will be ignored when release happens from the master branch.
- Update docs
- Remove unused parameter `parallel_test`
Every commit in the master branch runs the benchmark and saucelabs stages by default. Therefore, since the release happens from a particular commit in the master branch then it's not required to run those stages anymore.
=> ci(jenkins): release input parameters

Jenkinsfile
Enable slack notifications, similar to the email notifications, when a release is triggered.
Enable notifications if something bad happened with the release.
Ensure the right audience is in the loop.
the commit https://github.com/elastic/apm-agent-rum-js/pull/908/commits/24707b292729481c5041b5a248ee8be92706992f caused:
- Slack notification
- Email notification
=> ci(jenkins): enable slack notifications

packages/rum-core/src/common/compress.js, packages/rum-core/src/common/constants.js, packages/rum-core/src/performance-monitoring/performance-monitoring.js, packages/rum-core/src/performance-monitoring/span-base.js, packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
This PR add outcome to Transactions and Spans. The outcome is only added for `http-request` transactions since based on the definition of outcome we can only infer that for these type of transactions. For all other transactions the outcome is `unknown` which is set by the APM Server. See the original issue for more detail.
Fixes #876
=> feat: add span and transaction outcome

.github/stale.yml
Enable [stale bot](https://github.com/probot/stale) to notify and then close the Issues that haven't had any activity for 120 days, a notification will be sent after 100 days and if nothing else happens they will get closed 20 days later.
- Support `issues` only as stated
- It uses the `Stalled` label to categorise the ones that have been informed without any activity in 120 days.
- It looks for the issues that got the label `discuss` and `question`.
- Those `Stalled` issues will be closed if no further activity after 20 days.
- Those issues without a label are excluded from the bot. (There is no support for such). The workaround will be as simple as label them with `Stalled` then the bot will close them after 20 days.
Closes #912 
Relates to https://github.com/elastic/beats/pull/19157 …
=> chore: enable stale bot for issues

.ci/.jenkins_rum.yml, .ci/.jenkins_scope.yaml, .ci/.jenkins_stack_versions.yaml, .ci/docker/node-playwright/Dockerfile, .ci/docker/node-puppeteer/Dockerfile, .ci/scripts/test.sh, .gitignore, Jenkinsfile, dev-utils/docker-compose.yml, package-lock.json, package.json
It renames a shell script label to display a clearer name in the UI.
Minor improvements:
- Ignore .config and .npm from Git
- ~~Enforce pip3 when installing docker-compose (failed locally on my Mac)~~
>pip3 fails in the CI worker
- remove unused files
- bump `mime` dependency after running `npm install`
- join Saucelabs stage for PRs and merges to master, as they shared the same code
- Support building NodeJS 12 test images in a parameterised manner
- add descriptor file for nightly builds to build the Docker images, so that it's possible to consume them without building them on CI
- add a top-level script to run the unit tests by scope: `npm run test:unit`
```shell
$ SCOPE="@elastic/apm-rum-core" npm run test:unit
```
- Closes #932
- Relates …
=> chore(jenkins): minor refinements

.ci/packer_cache.sh
Fix an issue with the local prefix that's only supported for functions
Otherwise the packer cache automation won't cache those docker images
=> chore(jenkins): fix running issues with the packer-cache

packages/rum-core/src/error-logging/error-logging.js, packages/rum-core/test/error-logging/error-logging.spec.js
When reason is null, apm sdk crashes on evaluating `reason.message`.
=> fix: null is not an object (evaluating 'reason.message')

dev-utils/test-servers.js, docs/configuration.asciidoc, docs/distributed-tracing-guide.asciidoc, packages/rum-core/src/common/compress.js, packages/rum-core/src/common/config-service.js, packages/rum-core/src/common/utils.js, packages/rum-core/src/performance-monitoring/performance-monitoring.js, packages/rum-core/src/performance-monitoring/span-base.js, packages/rum-core/src/performance-monitoring/transaction-service.js, packages/rum-core/src/performance-monitoring/transaction.js, packages/rum-core/test/common/apm-server.spec.js, packages/rum-core/test/common/compress.spec.js, packages/rum-core/test/common/utils.spec.js, packages/rum-core/test/index.js, packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
+ fix #845 
+ Adds a new option `propagateTracestate` boolean to optionally add the tracestate header to all outgoing requests from the browser that are captured as transactions and spans . 
+ sent as `sample_rate` and `sr` in both v2 and v3 spec in the APM server. 
+ Updated the config doc and also CORS docs.
=> feat(rum): propagate sampling decision through tracestate

docs/angular-integration.asciidoc
Adds angular integration supported versions to reduce confusion. Per @vigneshshanmugam, Angular versions < 9 are supported.
Related to https://github.com/elastic/apm-agent-rum-js/issues/962.
=> docs: add angular supported version

Jenkinsfile
Use https://github.com/elastic/apm-pipeline-library/pull/976 to simplify the body manipulation
Need a the above-mentioned PR and also a release
=> ci: use the releaseNotification step

packages/rum/src/index.d.ts, packages/rum/test/types/index.spec.ts
+ exposes the configuration option type info which could be used by other internal packages or libraries. 
+ `@elastic/apm-rum-angular` can use this exposed interface to improve its `init` function
+ Added the `RegExp` to the distributedTracingOrigins types since we added the support recently.
=> feat(rum): expose agent configuration type info

.ci/jobs/defaults.yml
Use the default value for periodic-folder-trigger = `none`
> periodic-folder-trigger (str): How often to scan for new branches or pull/change requests. Valid values: 1m, 2m, 5m, 10m, 15m, 20m, 25m, 30m, 1h, 2h, 4h, 8h, 12h, 1d, 2d, 1w, 2w, 4w. (default none)
[docs](https://docs.openstack.org/infra/jenkins-job-builder/project_workflow_multibranch.html)
We don't need to build PRs when there is change in their target branch, the reason is reducing the number of resources needed in the cloud.
=> ci: jjbb remove periodic-folder-trigger

.ci/docker/node-playwright/Dockerfile
+ Fix the playwright webkit dependencies to run the benchmark script on master and on all PR's. 
```
Install missing packages with:
sudo apt-get install gstreamer1.0-libav
```
https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fapm-agent-rum-mbp/detail/PR-981/1/pipeline/
=> chore(benchmarks): fix playwright image dependencies

package-lock.json, package.json, packages/rum-angular/karma.conf.js, packages/rum-angular/src/apm.service.ts
+ Updates typescript to 3.8 for importing the type information and fix the build warnings as a result of that. 
+ Use the `AgentConfigOption` for initialising the service.
=> chore(rum-angular): fix build warnings in prod

packages/rum-core/src/performance-monitoring/metrics.js, packages/rum-core/src/performance-monitoring/transaction-service.js, packages/rum-core/test/performance-monitoring/metrics.spec.js
+ fix #988 
+ We filter all of the longtasks for the page load transaction that happened even before it to make sure we calculate all of the buffered long tasks as well starting from 0.
+ For all subsequent route-change transactions, we only account for long tasks that happened after the transaction start time. This ensures that we are not including all previous buffered long task entries. 
**As a result all of the managed transactions gets adjusted to the start time of the first span, Now all of the subsequent transaction timings would be wrong and broken in the UI**
=> fix(rum): discard longtask spans from prev transaction

packages/rum-core/test/common/xhr-patch.spec.js
+ Having public ips in the unit tests is flaky and would trigger disconnect errors like this - https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fapm-agent-rum-mbp/detail/PR-991/2/pipeline if the remote endpoint is having issues or changed. 
+ Disconnect is mainly due to these tests as the DNS query is more than 2 seconds. https://github.com/elastic/apm-agent-rum-js/blob/6b75589f0ed2c7fa90462396e256a9bc0e9ac33c/packages/rum-core/test/common/xhr-patch.spec.js#L139
=> chore: use local servers in unit test

packages/rum-core/src/performance-monitoring/metrics.js, packages/rum-core/src/performance-monitoring/transaction-service.js, packages/rum-core/test/performance-monitoring/metrics.spec.js
+ using `isHardNavigation` flag to distinguish hard and soft navigations to make it clear that we are capturing different observer entries for `page-load` and other transactions.
=> refactor: perf entries for hard & soft navigation

Jenkinsfile
Notify when things are not working before the release has even started
=> ci: notify when pre-release starts or fails

docs/angular-integration.asciidoc, packages/rum-angular/package.json
+ Major version ^2.x.x has been published, so we dont need the `alpha` flag anymore. 
+ cd directory is not required as lerna would use the `publishConfig.directory` while publishing contents.
=> chore: remove alpha from docs and cleanup

packages/rum-angular/CHANGELOG.md
+ States the message as 2.0 is deprecated and explaining why 2.0.1 is the recommended package.
=> chore: update angular changelog

.ci/bump-stack-release-version.sh, .ci/scripts/load-testing.sh, .ci/scripts/pull_and_build.sh, .ci/scripts/test.sh, Jenkinsfile, dev-utils/docker-compose.yml
* Bump version 7.10.0 to 7.13.1
* Script to bump release versions automatically
* Add this repo to the bump release automation
There is no a tracked issue for this particular PR. I identified this particular need when raising a couple of issues regarding build failures in the CI.
```bash
$ git checkout master
$ .ci/bump-stack-release-version.sh 7.13.1 7.13.2
```
produces
```diff
diff --git a/.ci/scripts/load-testing.sh b/.ci/scripts/load-testing.sh
index f77462d..4a09667 100755
--- a/.ci/scripts/load-testing.sh
+++ b/.ci/scripts/load-testing.sh
@@ -1,6 +1,6 @@
#!/usr/bin/env bash
-STACK_VERSION=${1:-7.10.0}
+STACK_VERSION=${1:-7.13.1}
USER_ID="$(id -u):$(id -g)"
NODEJS_VERSION=$(cat ./dev-utils/.node-version)
diff --git a/.ci/scripts/pull_and_build.sh b/.ci/scripts/pull_and_build.sh
index …
```
=> ci: bump elastic stack version

Jenkinsfile
The catchError is hidden and stage error so we need to force the stage result to know which stage is failing.
```
Benchmarks: there was a response with an error. Review response {"took":8,"errors":true,"items":[{"index":{"_index":"benchmarks-rum-load-test","_type":"_doc","_id":"3tGPJXoBfbEDP-36W9O7","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"not_x_content_exception","reason":"not_x_content_exception: Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes"}}}}]}
```
=> fix: set stage result

dev-utils/docker-compose.yml, dev-utils/test-servers.js, packages/rum-core/src/common/apm-server.js, packages/rum-core/src/common/compress.js, packages/rum-core/test/benchmarks/compress.bench.js, packages/rum-core/test/common/compress.spec.js, packages/rum/test/e2e/general-usecase/app.js
+ fix elastic/apm-agent-rum-js#1054 
+ When payload is compressed the `apmRequest` function was not sent correctly which made the function return `undefined` for all cases. Now we correctly propagate the function to all callers.
=> fix(rum-core): ensure apmRequest is called for events

Jenkinsfile
Use https://github.com/elastic/apm-pipeline-library/blob/master/vars/obltGitHubComments.txt
Avoid hardcoded strings and easy to normalise the GitHub comments in all the oblt projects
You can also see in the GitHub comment that there is a specific section for **some** of those GitHub comments called `🤖 GitHub comments`
=> chore: use obltGitHubComments in the pipeline

docs/configuration.asciidoc
Ensure limitations on naming are communicated for serviceName.
As per https://www.elastic.co/guide/en/apm/get-started/master/install-and-run.html#agents
=> docs: document allowed naming for serviceName

packages/rum-core/src/common/context.js, packages/rum-core/test/common/context.spec.js, packages/rum-core/test/performance-monitoring/capture-navigation.spec.js, packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
The intake API has deprecated the following fields from the span destination: `destination.service.type` and `destination.service.name` but until the intake API version 7.15 they are required anyway, so we need to include them in the request payload.
We have hardcoded empty string as a value. An important nuance here is that the value that is going to be send in the event payload for those fields is "N/A" since changing the truncate logic only for this requirement requires many modifications and in an upcoming release are going to be removed.
In the release 6.x we will [remove all the logic](https://github.com/elastic/apm-agent-rum-js/issues/1106) related with the deprecated fields because the intake API (from 7.15) will not require them anymore.
=> feat(rum-core): empty string for deprecated fields

docs/supported-technologies.asciidoc, packages/rum-core/src/performance-monitoring/performance-monitoring.js, packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
+ fix https://github.com/elastic/apm-agent-rum-js/issues/1091
adds support for custom user-interaction transaction names through custom data-attribute as explained here: https://github.com/elastic/apm-agent-rum-js/issues/1091
=> feat(rum-core): custom transaction name for user-interactions

.ci/scripts/load-testing.sh
This is an attempt to possibly avoid the following error when running a command such as `.ci/scripts/load-testing.sh 7.13.1`:
```
[2021-09-22T12:53:35.652Z] node-playwright        | found 672 vulnerabilities (481 low, 108 moderate, 83 high)
[2021-09-22T12:53:35.652Z] node-playwright        |   run `npm audit fix` to fix them, or `npm audit` for details
[2021-09-22T12:53:35.652Z] node-playwright        | + set -eo pipefail
[2021-09-22T12:53:35.652Z] node-playwright        | + npx lerna run build:main
[2021-09-22T12:53:36.351Z] node-playwright        | lerna notice cli v3.19.0
[2021-09-22T12:53:36.351Z] node-playwright        | lerna info versioning independent
[2021-09-22T12:53:36.351Z] node-playwright        | lerna info ci enabled
[2021-09-22T12:53:36.351Z] node-playwright        | lerna …
```
=> ci: simplify docker command to attempt to avoid occasional error

packages/rum-core/src/common/compress.js, packages/rum-core/test/common/compress.spec.js
In order to prevent the agent to throw an error when compressing transactions we are now checking the existence of navigation timing and agent marks.
Following the scout principle news tests added which check that marks are being compressed properly 👍
=> fix(rum-core): handle empty marks when compressing (#1104)

Jenkinsfile
* Use `7.16.0`
* Remove `7.x` reference
* Pass the STACK_VERSION to the function rather than using the environment variable.
Closes https://github.com/elastic/apm-agent-rum-js/issues/1111
Since `7.x` is not anymore a thing, what do we do with the 8 major since 8.0 branch exists and master points to 8.1 now.?
=> ci: bump stack versions

packages/rum-angular/src/apm.service.ts
The agent [documentation](https://www.elastic.co/guide/en/apm/agent/rum-js/current/angular-integration.html) indicates that the package @elastic/apm-rum-angular 2.x supports Angular versions ≥ 9.0.
The file containing the ApmService types declaration had an occurrence of import `type`. Such syntax is only available from TypeScript 3.8.x. This is important because angular 9.0.x only works with TypeScript 3.6 and 3.7. 
Note: Angular versions ≥ 9.1. are the first to be compatible with Typescript 3.8.x
Remove the `type` syntax.
=> fix(rum-angular): recover compatibility with angular 9.0.x

docs/agent-api.asciidoc, docs/intro.asciidoc, docs/set-up.asciidoc, docs/sourcemap.asciidoc, docs/transaction-api.asciidoc, docs/upgrading.asciidoc
Links updated as per elastic/observability-docs#1385. The old links will break when 7.17 releases. This PR and all backports must be merged before the 7.17 release. Thanks!
=> docs: update broken links for apm-guide-ref #1385

docs/agent-api.asciidoc, docs/intro.asciidoc, docs/set-up.asciidoc, docs/sourcemap.asciidoc, docs/transaction-api.asciidoc, docs/upgrading.asciidoc
Backports the pertinent bits of https://github.com/elastic/apm-agent-rum-js/pull/1143 to 5.x.
=> docs: 5.x link fixes

docs/agent-api.asciidoc, docs/intro.asciidoc, docs/set-up.asciidoc, docs/sourcemap.asciidoc, docs/transaction-api.asciidoc, docs/upgrading.asciidoc
Backports the pertinent bits of https://github.com/elastic/apm-agent-rum-js/pull/1143 to 4.x
=> docs: 4.x link fixes

dev-utils/build.js, package-lock.json, package.json, packages/rum-react/test/polyfills.js, scripts/license-checker.js
This fixes dependencies that were pointed out by our automations as needing updates.
Please notice that even though all the dependencies pointed out were dev dependencies, we still update them as they could impact the build, and thus they also need checking. Also, we had to force some downstream dependencies to resolve to particular versions, such as `lodash` and `semver-regex`. For that, we used [`npm-force-resolutions`](https://github.com/rogeriochaves/npm-force-resolutions).
@devcorpio has helped me update these dependencies (thank you 🙌 ) and will help me out with testing this on the RUM agent itself as he's more experienced with this codebase.
We also want to ensure CI is passing, which is why we created this PR early.
=> chore: update dependencies pointed out by our automations

docs/upgrading.asciidoc
Updates a link to the [APM Server 7.0 upgrade guide](https://www.elastic.co/guide/en/apm/guide/7.17/upgrading-to-70.html). This link doesn't exist in 8.0+ and will break when we release 8.0 GA.
**NOTE:** The link currently directs users to 7.17 so we may want to wait until after the 7.17 release before merging.
We'll also need to backport to 5.x.
Relates to https://github.com/elastic/docs/pull/2312
https://apm-agent-rum-js_1153.docs-preview.app.elstc.co/guide/en/apm/agent/rum-js/master/upgrade-to-v5.html#v5-upgrade-server
=> docs: update link to APM server 7.0 upgrade guide

docs/upgrading.asciidoc
Backports https://github.com/elastic/apm-agent-rum-js/pull/1153 to 5.x
=> docs: update link to APM server 7.0 upgrade guide (#1153)

packages/rum-core/src/common/patching/event-target-patch.js, packages/rum-core/test/common/event-target-patch.spec.js, packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
Web applications which rely on event delegation tend to declare click events through these ways:
```
window.addEventListener('click', //...)
document.addEventListener('click', //...)
document.querySelector("div.root").addEventListener('click', //...)
// more strategies ...
```
The agent is not handling  properly these cases. In our instrumentation we are not using the [target](https://developer.mozilla.org/en-US/docs/Web/API/Event/target) to build the user interaction transaction. Instead what we are doing is to use the equivalent to [currentTarget](https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget)
since we define the target as the element where the listener is being attached
The fix consists in capture the event generated by the browser and pick the target property …
=> fix: identify on which element occurred a click event

.ci/scripts/load-testing.sh, .ci/scripts/pull_and_build.sh, .ci/scripts/test.sh, Jenkinsfile, dev-utils/docker-compose.yml
=> chore: update elastic stack release version 7.17.0 7.17.1

package-lock.json
Hypothesis: The only change we made in February 14th was this [one](https://github.com/elastic/apm-agent-rum-js/pull/1167). Reverting in order to know if was the cause of the [issue](https://github.com/elastic/apm-agent-rum-js/issues/1178) with the benchmark
=> chore: revert bump ajv from 6.10.0 to 6.12.6 (#1167)

dev-utils/docker-compose.yml
=> chore: fix benchmark in the CI

packages/rum-core/test/common/page-visibility.spec.js, packages/rum-core/test/index.js, packages/rum/test/specs/apm-base.spec.js
Test that demonstrates that if a page becomes backgrounded all the data gathered until that moment will be sent even when the load event from the browser has not been triggered.
=> chore: test for partial page-load transaction

.ci/jobs/defaults.yml, Jenkinsfile
This proposal reduces:
* The builds for tags.
* Benchmark to run on `main` but no tags
* Tests to run for all but `main`
Tags are generated always from a particular merged commit, and merged-commits are validated always in the main branch, and previous to be merged on a PR basis.
Therefore there is no need to generate heavy builds in favour of simplifying the releases.
Opbeans are updated automatically at the very end of the release, so by making more reliable then the opbeans can benefit from the autoamtion in place.
Relates to https://github.com/elastic/apm-agent-rum-js/issues/1191
=> ci: simpler builds for tag releases

.ci/bump-stack-release-version.sh, Jenkinsfile
- ~~Bump versions to `8.1` and `7.17`~~ requires https://github.com/elastic/apm-agent-rum-js/pull/1193
- Fix version bump (since `7.x` is not anymore a pattern to be searched)
- Use [`retryWithSleep`](https://github.com/elastic/apm-pipeline-library/blob/main/vars/retryWithSleep.groovy) to simplify the pipeline
- Use [`withNode`](https://github.com/elastic/apm-pipeline-library/blob/main/vars/withNode.groovy) to assign unique agents.
Trying to solve the issue with the `Test Puppeteer` when the subsequent reattempts triggered by the test command fail. I'm still confused since `Test Puppeteer` does not cache anything in the CI workers, and the `Gobld Jenkins plugin` ensures the workers are not reused.
=> ci: use withNode and use retryWithSleep

packages/rum/package.json
Otherwise, there are failures in the CI pipeline:
```
[2022-04-11T10:05:14.386Z] @elastic/apm-rum:  FAIL  ./dist/bundles/elastic-apm-rum.umd.min.js: 19.4KB > maxSize 19KB (gzip) 
[2022-04-11T10:05:14.386Z] @elastic/apm-rum:  FAIL  ./dist/bundles/elastic-apm-opentracing.umd.min.js: 20.95KB > maxSize 20.5KB (gzip)
```
=> chore: increase bundle size limit

packages/rum-core/src/performance-monitoring/transaction.js, packages/rum-core/test/performance-monitoring/transaction.spec.js
Relates to: https://github.com/elastic/apm-agent-rum-js/issues/1196
With this change we make sure that the reuseThreshold is overridden every time a transaction is redefined. This change will benefit users browsing with slow networks in cases like the one explained [here](https://github.com/elastic/apm-agent-rum-js/issues/1196#issuecomment-1097908486)
https://user-images.githubusercontent.com/15065076/164041735-b5299857-3959-4c04-aaf7-a495b3eca118.mov
@vigneshshanmugam I added feat(rum) in the commit. If you think that this should be a **"chore:"** instead let me know
=> feat(rum): override threshold when redefining transaction

packages/rum-core/src/common/constants.js, packages/rum-core/src/common/patching/fetch-patch.js, packages/rum-core/src/performance-monitoring/performance-monitoring.js, packages/rum-core/test/common/fetch-patch.spec.js, packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
Relates to: https://github.com/elastic/apm-agent-rum-js/issues/1210
The goal of this change is to set the outcome of transactions/spans with aborted requests to **unknown**
@vigneshshanmugam:
There is some **drawback** that I would like to highlight related to Fetch API: 
At present, it's not possible to tell if the request has aborted with a timeout or not. It means, that we would be treating as "unknown" (rather than a failure) the ones that are caused by a timeout. Although, the agent currently consider them as a **successful** ones, so we could consider this as an improvement? (thinking out loud  🤔 )
There are upcoming browser APIs that will address that, such as: [AbortSignal.timeout](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/timeout). For instance, it will be …
=> feat(rum): set unknown outcome for aborted http requests

packages/rum-core/src/common/patching/fetch-patch.js, packages/rum-core/test/common/fetch-patch.spec.js
From now on, fetch spans will be ended once the response stream is completely consumed.
- Browser not supporting [ReadableStream](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream) will keep working as they were already doing.
- If the server triggers an error while emitting chunks of data, the logic in charge of reading the stream will notice and then the transaction/span outcome will be set as a **failure**
- If the request is aborted while reading the stream, the transaction/span outcome will be set as a **unknown** (following the strategy started in a [previous PR](https://github.com/elastic/apm-agent-rum-js/pull/1211))
The memory analysis have not reported anything grave. A local website (always in incognito, without extensions) have been tested in the following …
=> fix(rum): end fetch span when response stream ends

Jenkinsfile
https://github.com/elastic/apm-agent-rum-js/pull/1201 caused a regression while reporting the test errors since the post-build in the matrix stage was not moved to the script itself.
=> ci: report back test results

docs/troubleshooting.asciidoc, packages/rum-core/src/common/compress.js, packages/rum-core/src/common/utils.js, packages/rum-core/test/common/compress.spec.js, packages/rum-core/test/common/utils.spec.js
In the past it has been common to find the situation where we needed a HAR file to investigate issues of a support case.
Most of the time the HAR files provided were not showing the payload of the events sent by the RUM agent. That was happening because they were generated in **Chrome**. That browser supports **Compression Streams API** which it is being used by the agent to compress events payload. Although it would be possible to generate them with a browser such as Firefox, we have found that in particular cases that wasn't a viable option for support.
Because of that, in a conversation with @vigneshshanmugam we agreed to provide a way of disabling payload compression for such scenarios.
Disables the payload compression:
1.  if an item with the key `_elastic_inspect_beacon_` exists in …
=> feat(rum): disable beacon compression when flag is set

CHANGELOG.asciidoc
- Release notes for 5.11.1
When updating 5.x branch docs, I will make sure of adding:
- the changes of this PR
- the changes done in [troubleshooting docs](https://github.com/elastic/apm-agent-rum-js/pull/1214/files?short_path=92b8b79#diff-92b8b7986e2fd45aa4cb15ef8868e24f3470b2f0f17a9ab88c1b95f1357e0b6c).  (**DONE**)
- the changes done in [disableInstrumentation docs](https://github.com/elastic/apm-agent-rum-js/pull/1219/files?short_path=df7480c#diff-df7480cd30746f32771991c28c14e275c3d46e989be2be5da8cfc6f9a1b02eb7) (**DONE**)
=> docs: add release notes for 5.11.1

package-lock.json, package.json
Reverts dependabot `[update](https://github.com/elastic/apm-agent-rum-js/pull/1221)` 
Reasons:
- Causes a failure in benchmark results template
- We don't need the update
=> chore: revert dependabot update

CHANGELOG.asciidoc
- Update docs to have proper [asciidoc](https://asciidoc.org/) syntax
=> docs: update 5.11.1 release notes

CHANGELOG.asciidoc
In the 5.11.0 release notes we explained that the [new beaconing feature ](https://www.elastic.co/guide/en/apm/agent/rum-js/current/release-notes-5.x.html#_features_2) was sending all events. Nevertheless, there is a nuance that we didn't include in the description. [Custom unmanaged transactions](https://github.com/elastic/apm-agent-rum-js/issues/1231) are not handled by that feature.
This PR updates the release notes to highlight that only managed transactions are considered.
=> docs: amend release 5.11.0 notes

packages/rum-core/src/common/config-service.js, packages/rum-core/test/common/config-service.spec.js, packages/rum/src/apm-base.js, packages/rum/test/specs/apm-base.spec.js
closes #1228 
Check the config options and print warnings when unknown config options are specified. 
As mentioned in the ticket, we won't affect any initiation logic but keep permitting the agent to be activated.
=> feat: warn users when invalid config options provided when init

docs/configuration.asciidoc, packages/rum-core/src/common/apm-server.js, packages/rum-core/src/common/config-service.js, packages/rum-core/src/common/http/fetch.js, packages/rum-core/src/common/http/xhr.js, packages/rum-core/test/common/apm-server.spec.js, packages/rum-core/test/common/http/fetch.spec.js
fix #1237 
This allows RUM clients to send cookies to APM servers that are behind reverse proxies that require requests to be authenticated.
=> feat: allow requests to be sent with credentials

docs/set-up.asciidoc
This PR follows up the [one](https://github.com/elastic/apm-agent-rum-js/pull/1238) which added the new config for sending credentials.
The added changes would look like the screenshot below:
The current version is available in this [link](https://www.elastic.co/guide/en/apm/agent/rum-js/5.x/configuring-cors.html)
=> docs: update cors documentation

packages/rum-core/src/error-logging/error-logging.js, packages/rum-core/src/error-logging/stack-trace.js, packages/rum-core/test/error-logging/stack-trace.spec.js
The RUM agent was capturing errors thrown in [inline scripts](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#examples) with an **empty stack trace**.  There is a nuance to highlight, though.
This **only** affects to errors whose type is [SyntaxError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError) and have been triggered because of a malformed JavaScript code. This tend to occur when the browser is parsing the document.
The following two examples will help to understand that nuance:
Example 1 (**KO**): SyntaxError because of malformed JavaScript while parsing the document:
```
<html>
<head>Example 1: SyntaxError because of malformed JavaScript while parsing the document </head>
<body>
Hello, I am Example 1 page.
<script>
var …
```
=> fix(rum-core): capture stack trace from syntax errors properly

packages/rum/src/index.d.ts
elastic/apm-agent-rum-js#1238 added the `sendCredentials` option, but it didn't add it to the Typescript definitions file. This fixes that oversight.
=> feat(rum): add sendCredentials config to TypeScript typings

package-lock.json, package.json
**Agent maintenance:**
A few months ago, in this [PR](https://github.com/elastic/apm-agent-rum-js/pull/1131), we introduced [npm-force-resolutions](https://github.com/rogeriochaves/npm-force-resolutions) to the project.
We did to force some downstream dependencies to resolve to particular versions, such as lodash and semver-regex.
**Why removing this now?**
1. The developer experience when doing commits (including amends) is not good. The process is quite slow and feels intrusive. 
2. Apart from that, none of the dependencies locked end up on the bundle used by our users/customers, all the locked versions are devDependencies.
3. It requires from us to keep track of **two** kind of versions: the ones of the installed packages and the ones related to the resolution.
Those are the main …
=> chore: remove script to lock dependency version

docs/troubleshooting.asciidoc
To improve the guidance we provide to our users and customers we are updating the [troubleshooting](https://www.elastic.co/guide/en/apm/agent/rum-js/master/troubleshooting.html) page explaining why sometimes the only information available for a JavaScript error is "Script error". The new docs also include the steps needed to fix the situation.
The most recent example of this issue can be seen at [this](https://elastic.slack.com/archives/C0D1XEXEZ/p1655216496061709?thread_ts=1648034147.903139&cid=C0D1XEXEZ) slack conversation with @jstrassb
=> docs: add cross-origin script error details

packages/rum-core/src/performance-monitoring/metrics.js, packages/rum-core/test/performance-monitoring/metrics.spec.js
fixes #1245 
This PR checks `PerformanceObserver.supportedEntryTypes` before starting an observer for a certain entryType so that it doesn't print a warning on Firefox browser and doesn't trigger errors on Safari when it starts observer for unsupported types.
Before the change on Firefox (latest version):
[![Image from Gyazo](https://i.gyazo.com/86731cfbb03863cbb454a57400d1d8db.gif)](https://gyazo.com/86731cfbb03863cbb454a57400d1d8db)
After the change on Firefox (local build of this PR):
<a href="https://gyazo.com/8324a6d181070ed09d4933651597428a"><img src="https://i.gyazo.com/8324a6d181070ed09d4933651597428a.gif" alt="Image from Gyazo" width="986"/></a>
List of supported entry types:
- Chrome (102.0): 
`['element', 'event', 'first-input', 'largest-contentful-paint', 'layout-shift', …
=> fix: check supportedEntryTypes when starting observer

packages/rum/src/index.d.ts
@hmdhk you had forgotten the typescript files, can you please check if it fits like this
the feature is great and we use it, thanks for your effort
=> feat(rum-core): add apmRequest config typescript type

scripts/apm-server-load-test.js, scripts/benchmarks.js
[Recently](https://elastic.slack.com/archives/C5L79P420/p1658250637879769) the deployment of our benchmarks deployment was upgraded from 7.x to 8.x. The new version does not support mapping [types](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/removal-of-types.html) and since we were including a "_type" property on our document the benchmark process was not ending properly
The "_type" field will not be stored anymore
Thanks @trentm for the heads up
=> chore: remove _type from benchmark document

dev-utils/test-config.js
The **apm-rum-vue** e2e tests were failing because of the following combination:
_Mozilla recently [removed the ability](https://github.com/mozilla/geckodriver/issues/2011) to pass the capability --remote-debugging-port in Firefox GeckoDriver version 0.31.0._
and
_On October 4, 2022, Sauce Labs updated the supported Firefox GeckoDriver to version 0.31.0 for tests on Firefox versions 90 and later. If you use the –remote-debugging-port capability, your tests will fail if you do not take action before October 4, 2022._
More info [here](https://saucelabs.com/blog/update-firefox-tests-before-oct-4-2022)
The cleanest fix for this would be to update to a new version of karma-sauce-launcher. Unfortunately, a new version available with the updated …
=> chore: saucelabs firefox update

Jenkinsfile, package-lock.json, package.json
**bundlesize** depends on a version of **brotli** that depends on **iltorb 2.4.5** which is an archived repo and it's failing with Node.js 14
This change is [recommended](https://github.com/siddharthkp/bundlesize/pull/370#issuecomment-1038968845) by the author of bundlesize.
=> chore: replace bundlesize with bundlesize2

.ci/docker/node-playwright/Dockerfile
Chrome 109 was causing Karma to crash when executing the benchmarks. The dependency that was installing such version is **google-chrome-unstable**.
The only visible log in the CI was **"Cannot start ChromeHeadless",** no useful details related to the error were provided.
To fix this situation we have replaced **google-chrome-unstable** with **google-chrome-stable**. Now, the version installed is **107**, which works perfectly.
We are not exactly sure why Chrome **109** was failing, that version will be [released](https://chromiumdash.appspot.com/schedule) in 2023, so probably there are bugs that Chrome contributors need to fix. If the benchmarks start failing in **2023** for the same reason we will need to approach this issue in a different way.
=> chore: use chrome stable to execute benchmarks

.github/workflows/bump-elastic-stack.yml
Use GitHub composite action
Reuse code and solve the existing issue with Workflows won't be enabled for PRs created on behalf of `GitHub actions [bot]`, see https://github.com/elastic/ecs-logging-java/pull/200
Similar to https://github.com/elastic/ecs-logging-java/pull/201
Requires https://github.com/elastic/apm-pipeline-library/pull/2076
=> chore: use composite updatecli github action

docs/configuration.asciidoc
The Kibana endpoint is no longer required for APM agent central configuration.
For https://github.com/elastic/apm-server/issues/9982.
=> docs: remove kibana endpoint

docs/supported-technologies.asciidoc
The goal of this documentation update is to highlight two things:
- RUM framework specific integration is a recommendation and not a requirement
- Enumerate the reasons why we recommend framework specific integration (Vue, React, Angular)
@vigneshshanmugam as we discussed a few days ago, the changes are added to the [frameworks](https://www.elastic.co/guide/en/apm/agent/rum-js/current/supported-technologies.html#frameworks) section of the [supported technologies page](https://www.elastic.co/guide/en/apm/agent/rum-js/current/supported-technologies.html)
Screenshot of the preview (edit: includes Paul's suggestions):
=> docs: update framework integrations docs

.github/workflows/ci.yml
Only docs PR cannot be merged because the `Lint` status check is not created. 
However, the `all` status check is created because of the `ci-docs.yml` workflow.
Reference: https://github.com/elastic/apm-agent-rum-js/pull/1375#issuecomment-1589924749
This PR create a single status check named `all` in both only-docs and code changes which can then be set as required.
Adjust branch protection rules shortly before merging:
- Add `all` as required status check
- Remove `Lint` as required status check
=> Fix status checks

docs/agent-api.asciidoc, docs/sourcemap.asciidoc, docs/transaction-api.asciidoc
This PR fixes the links broken in https://github.com/elastic/apm-server/pull/10894.
A list of broken links is here https://github.com/elastic/apm-server/pull/10891#issuecomment-1563004781.
=> docs: fix links

.github/workflows/release.yml, Jenkinsfile, RELEASE.md, package.json, scripts/ci-prepare-release.js
* Migrate release pipeline from Jenkins to GitHub Actions
* Jenkins is deprecated
* It has been tested with another Google Cloud Account
* https://github.com/elastic/apm-agent-rum-js/actions/runs/5203874294
=> ci: initial ci release to gh

.ci/bump-elastic-stack.yml, .ci/scripts/bench.sh, .github/workflows/microbenchmark.yml, .github/workflows/opentelemetry.yml, Jenkinsfile, dev-utils/docker-compose.yml, dev-utils/kibana/kibana.yml, scripts/apm-server-load-test.js, scripts/benchmarks.js
* Migrate microbenchmarking from Jenkins to GitHub Actions and Buildkite.
* Correct broken load testing and benchmarking reporting.
* Add automation to bump stack version in the microbenchmark workflow.
* Cleanup `Jenkinsfile` before last migration step.
* Jenkins is deprecated.
* The microbenchmark reporting is broken.
* https://github.com/elastic/apm-agent-rum-js/actions/runs/5393533277/jobs/9793402071
=> ci: initial microbenchmark migration to GitHub Actions

packages/rum-angular/package.json, packages/rum-angular/tsconfig.lib.prod.json
Related to https://github.com/elastic/apm-agent-rum-js/issues/1345
The changes in this PR will make it possible to use Angular RUM integration in Angular **Ivy** Applications, including Angular 16.
E2E tests work properly in each of the browsers we support.
**Angular 16 app using RUM agent WITHOUT the changes**
**Angular 16 app using RUM agent WITH the changes**
--
**The new changes are only compatible with Angular >=12.**
**Note**: From Angular 12 is not possible to disable Ivy
See below the behaviour with older versions:
Angular 9 output:
Angular 10 output
Angular 11 output
Bear in mind that there are other ways to test this, but this is my favourite way (closer to the reality, users install packages):
1. Checkout the PR's branch
2. Install …
=> feat(rum-angular)!: support angular ivy

packages/rum-core/src/performance-monitoring/breakdown.js, packages/rum-core/test/common/apm-server.spec.js, packages/rum-core/test/performance-monitoring/breakdown.spec.js, packages/rum-core/test/performance-monitoring/transaction-service.spec.js
Fixes https://github.com/elastic/apm-agent-rum-js/issues/1360
From now on, the breakdown metric `span.self_time.sum.us` will be calculated in microseconds.
By the way, although this is not a 100% sure breaking change - we don't know what users might do with the ingested data), it can be a "potentially breaking change", so we should indicate it.
For instance, I like how the Java APM agent team expresses that concept in their release notes:
Example [here](https://www.elastic.co/guide/en/apm/agent/java/current/release-notes-1.x.html#_potentially_breaking_changes)
**Important:** 
You will see that I've not updated the calculation for `transaction.duration.sum.us`. The reason is that almost two years ago, [APM server stopped recording that …
=> fix(rum): report breakdown span time in microseconds

packages/rum-core/src/common/compress.js, packages/rum-core/src/performance-monitoring/breakdown.js, packages/rum-core/test/common/apm-server.spec.js, packages/rum-core/test/performance-monitoring/breakdown.spec.js, packages/rum-core/test/performance-monitoring/transaction-service.spec.js, scripts/ci-bundlesize.sh
Follow up / Continuation of https://github.com/elastic/apm-agent-rum-js/pull/1381
Almost two years ago,  [APM server stopped](https://github.com/elastic/apm-server/issues/6176) recording **transaction.duration.sum.us** and **transaction.duration.count**. 
The [context](https://github.com/elastic/apm/issues/505) for that is this:
> Agents capture and send transaction.duration.sum.us and transaction.duration.count metrics to apm-server, which we have been dutifully recording as part of transaction breakdown metrics. The original intention behind these was to enable metrics-based UI.
> 
> We now capture transaction latency distributions in apm-server, so the above mentioned metrics are no longer needed. They're not used anywhere, so let's stop recording them.
> 
> Additionally, …
=> fix(rum): stop recording transaction breakdown metrics

packages/rum-angular/README.md
Dummy commit to force the breaking change when doing the angular package release, added the 1380 identifier, so future explorers can find the original PR
BREAKING CHANGE: add angular ivy support
=> feat(rum-angular)!: support angular ivy (#1380)

lerna.json
**Important**: this fixes our problems with Lerna generating the wrong bump of package versions.
Before the change, it wasn't possible to add a breaking change just for one package since the conventions were not working as expected. The breaking change bump was being propagated to the main rum package which was totally wrong.
This was the output:
```
...
@elastic/apm-rum-angular@2.1.7 > - @elastic/apm-rum-angular@3.0.0
@elastic/apm-rum@5.12.0 > @elastic/apm-rum@6.0.0
...
```
Because of that, previous breaking changes of integration packages were published manually.
From now on, we will start using the preset that handles all our commits properly. Now the output is:
```
...
- @elastic/apm-rum-angular@2.1.7 => 3.0.0
- @elastic/apm-rum@5.12.0 => 5.13.0
...
```
Those are the correct versions …
=> chore: use conventionalcommits changelog preset

.github/workflows/ci.yml, package.json, scripts/ci-release-dry-run.sh
At present, the only non-manual way to know what versions are generated for the tooling we use (lerna + [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)) is performing a release.
It's true that when we had Jenkins, the release process allowed:
- visualize the generated versions
- and allow a human to confirm if they were the proper ones
Now that we are using Github actions the process has changed, and the manual confirmation is not there anymore. The reason is that it’s more complicated (from the technical standpoint) to wait for a human action within GitHub Action.
What is more, with the recent permission changes, once a commit has been merged into the main it's not possible (unless you ask someone with those permissions) to amend it in case something inconvenient …
=> chore: add release dry run step

.github/workflows/ci-saucelabs.yml, packages/rum-core/src/common/observers/page-clicks.js, packages/rum-core/test/common/observers/page-clicks.spec.js, packages/rum/src/index.d.ts
Related to https://github.com/elastic/apm-agent-rum-js/issues/1286
We have improved the user-interaction transaction name obtaining. From now on, if a user performs click on an element from a nested HTML structure like this:
```
<button data-transaction-name="my transaction name">
<span>Some text</span>
<svg>button icon...</svg>
</button>
```
The users will always get  `Click - my transaction name ` rather than `Click - span` or `Click - svg`
For more details see the [issue](https://github.com/elastic/apm-agent-rum-js/issues/1286)
**Important**: 
The agent will keep applying the older "algorithm" in browsers not supporting the closest method. E.g. IE11
In addition, this will work if the target is inside a button or link - the ones we define as interactive selectors. See [the associated …
=> feat(rum-core): enhance user transaction name obtaining

CHANGELOG.asciidoc, docs/angular-integration.asciidoc
- Release notes for 5.13.0
**PREVIEW**
--
Additionally, I updated the docs for Angular, preview here:
P.S. Once this is merged, I will also update the docs for 5.x branch
=> docs: update 5.13.0 release notes

packages/rum-core/src/common/patching/fetch-patch.js, packages/rum-core/test/common/fetch-patch.spec.js
this contribution has been made by @alizeait in the following PR: https://github.com/elastic/apm-agent-rum-js/pull/1373
The reason for creating this PR is to force the new CI mechanism to execute the E2E Saucelabs tests, which at this moment are not being executed for PRs coming from forks: CC: @amannocci 
Thanks again to @alizeait for taking the time to make these changes.
For additional visibility, the contribution resolves https://github.com/elastic/apm-agent-rum-js/issues/1288 and https://github.com/elastic/apm-agent-rum-js/issues/1396
--
Additional context:
Example of fetch with URL object
```
fetch(new URL("http://localhost:3000/api_test_post"), {
method: "POST",
headers: {
Authorization: `Bearer test`,
},
})
```
**Before the change**, and since the fetch patch didn't handle URL …
=> fix(rum-core): add URL object support in fetch instrumentation

.github/workflows/release.yml
The PR changes prevent the dry-run release process from sending Slack notification
=> chore: prevent slack notification in dry-run mode

packages/rum/src/index.js
Lerna **will not** bump the minor version of a package if there are no files modified within that specific package, even if the commit contain "feat(specific-package)"
That is understandable from a technical standpoint but not from a user standpoint, at least in the case of **rum-core** and **rum**
The upcoming release among other things will contain a new feature ([the redirect span](https://github.com/elastic/apm-agent-rum-js/pull/1400)). The logic modified belongs to rum-core, so it's generating a minor bump in the package rum-core, but not in the one that **users will download** (apm-rum), so instead of **5.13.1** as it was generating it should create **5.14.0.** to clearly highlight that contains a new feature.
Needless to say that it wasn't the end of the world, in the past we have …
=> feat(rum): force minor version bump rum package

.github/workflows/release.yml
* The auto-generate github token isn't enough to push on protected branches.
* We should be able to push on protected branches for release process.
=> ci: correct github token configuration

.github/workflows/release.yml
* Use github user data to setup git
* The auto-generate github token was used 
* We aren't able to publish a release using the auto-generate token since it can't be associated with a user.
=> ci: setup git using github user data

.github/workflows/release.yml
* Use the PAT GitHub Token to checkout the repository.
* It will persist the PAT token instead of the default one.
* lerna isn't able to push on protected branches.
=> ci: avoid to persist the wrong GitHub token

docs/react-integration.asciidoc
Associated to: https://github.com/elastic/apm-agent-rum-js/pull/1410
**Note**: merge once the [new react package version](https://github.com/elastic/apm-agent-rum-js/pull/1410) has been released
Adds the `<ApmRoutes>` component to the [React docs](https://www.elastic.co/guide/en/apm/agent/rum-js/current/react-integration.html).
Preview:
--
and
--
=> docs: update react docs

docs/sourcemap.asciidoc
Changes `{apm-guide-ref}//source-map-how-to.html` to `{apm-guide-ref}/source-map-how-to.html`
=> docs: Removes // from source map link

docs/agent-api.asciidoc
fixes typo: transaciton => transaction
=> docs: fix typo in agent-api docs

dev-utils/test-config.js
There is a bug when executing tests against IE 11 (Platform Window 8.1)
Although the tests pass, the CLI process runs indefinitely with this log:
`
"Check if 'log.json' for browser 'internet explorer 11 Windows 8.1' has already been stored."
`
That also means that the CI process never ends.
Debugging I found that by changing the platform from Windows 8.1 to Windows 10, the problem goes away.
I also reported this bug to SauceLabs Support with all this info (and a few links to the corresponding executions). Also highlighted to them that this is a regression because it wasn't happening before
**Edit**: Saucelabs confirmed the bug. Their engineers are working on a solution.
=> chore: upgrade ie11 windows os for saucelabs

.github/workflows/snapshoty.yml, package.json
The [Snapshoty github action](https://github.com/elastic/apm-agent-rum-js/actions/workflows/snapshoty.yml) has been failing for a week.
The underlying process execute "npx lerna ...".
The "npx" command is installing a new version of lerna (7.3) which assumes that the Node.js version of the environment supports modern syntax such as "??".  (one week before it was using 7.2)
https://github.com/elastic/apm-agent-rum-js/actions/runs/6236074031/job/16972772623
I'm removing the NPX statement and using the lerna we have already in the project.
Since now we will use our own lerna, I'm installing dependencies @amannocci any thoughts here? is this okay?
=> chore: stop using npx lerna in ci

.github/workflows/release.yml
This was already implemented in Jenkins see https://github.com/elastic/apm-agent-rum-js/pull/793/files\#diff-e6ffa5dc854b843b3ee3c3c28f8eae2f436c2df2b1ca299cca1fa5982e390cf8R399
Uses `headers - (Optional) Set object metadata.` as explained in https://github.com/google-github-actions/upload-cloud-storage
A leftover from the CI migration
=> ci: support headers in the CDN google bucket

packages/rum-core/src/performance-monitoring/navigation/capture-navigation.js, packages/rum-core/test/performance-monitoring/capture-navigation.spec.js
Fixes: #1430
This PR fixes a duration discrepancy with sampled and unsampled `PAGE_LOAD` transactions. 
Unlike **unsampled** transactions, sampled ones capture navigation metrics (and that is where we set the start to 0).
It has been detected that the difference in behaviour between sampled and unsampled was affecting the page load duration reported by the agent.
Please, [see the issue](https://github.com/elastic/apm-agent-rum-js/issues/1430), which provides an exemplary description, for more details.
Make sure the unsampled page load transactions start is set to 0, too.
Unsampled page load transactions are not taken into account in the User Experience Page. This means this fix will not affect anything there. This fix might affect existing custom boards created by users. Thanks …
=> fix(rum-core): unsampled page load transaction start must be zero

.github/workflows/release.yml
The Google github action named [upload-cloud-storage](https://github.com/google-github-actions/upload-cloud-storage) expects the name of the headers in lowercase.
With this change, we intend to solve the CDN upload step in the release process: https://github.com/elastic/apm-agent-rum-js/actions/runs/6317518826/job/17154464506
=> ci: rewrite google cdn headers in lowercase

.github/workflows/release.yml, scripts/ci-release.mjs
To verify if lerna publish in CI is also modifying the .npmrc file.
- release disabled. Added a git status to see if the worktree is clean, if that's the case, will add a statement to tell git to ignore modifications in the .npmrc in the release process (right now we are just doing that in the dry run mode)
- release notification status disabled in order to avoid being noisy
=> ci: debug non-dry-run release mode

.github/workflows/release.yml, scripts/ci-release.mjs
If we want to make sure .npmrc modifications don't affect the lerna release, we should tell git to ignore the modifications with `git update-index --no-skip-worktree .npmrc ` 
At this point, we still have the release and notifications disabled to avoid being noisy
=> ci: ignore git uncommitted changes when releasing

.github/workflows/release.yml, scripts/ci-release.mjs
This PR is the last step of the prod-release troubleshooting process:
These are the previous ones:
1. https://github.com/elastic/apm-agent-rum-js/pull/1440
2. https://github.com/elastic/apm-agent-rum-js/pull/1441
with all these changes the file `.npmrc` will not give problems anymore when Lerna releases the agent
=> ci: enable prod release mode

scripts/ci-pre-release.mjs
Fixes the issue when running the pre-release step with `dry-run`.
Ideally, https://github.com/cli/cli/issues/8375 will help with the dry-run.
See https://github.com/elastic/apm-agent-rum-js/actions/runs/7503019059
=> ci(release): support dry-run

docs/intro.asciidoc, docs/supported-technologies.asciidoc
Related to https://github.com/elastic/observability-docs/issues/3424, https://github.com/elastic/observability-docs/pull/3531
Adds information on interaction to next paint (INP) metrics.
It wasn't clear if the agent will stop collecting first input delay (FID) data or if the UI just won't display it anymore in stack version 8.12 and higher. Should the info on First input delay (FID) be removed or should it stay? (I just commented it out for now.)
=> docs: Add info on INP

.github/workflows/opentelemetry.yml
No need to maintain the static list of GitHub Workflows to be monitored with the CI/CD Observability using Opentelemetry
=> ci(github-action): use wildcards for discovering all the workflows

.github/workflows/release.yml, package.json, scripts/ci-post-release.mjs
Run `post-release` step at the very end of the release.
Tag all the Lerna modules using the sha commit for the tag release `@elastic/apm-rum-core`
```bash
$ GITHUB_TOKEN=$(gh auth token) DRY_RUN=false npm run ci:post-release
```
It produced the below output:
```
> elastic-apm-rum@0.0.0-monorepo ci:post-release
> node ./scripts/ci-post-release.mjs
Git User: username=Victor Martinez, email=VictorMartinezRubio@gmail.com
Running in prod mode
> List lerna versions
lerna notice cli v4.0.0
lerna info versioning independent
lerna success found 5 packages
>> Get sha commit for @elastic/apm-rum-core@5.21.0
>> @elastic/apm-rum-core@5.21.0 = 242cb41a092b88a3e832fdaf9bb970b7b8d272cf
Note: switching to '242cb41a092b88a3e832fdaf9bb970b7b8d272cf'.
You are in 'detached HEAD' state. You can look around, …
```
=> ci(post-release): tag the lerna packages

.github/workflows/ci-saucelabs.yml
This workflow triggers another job always, so this should help with avoiding reporting any failures if `test-saucelabs` didn't get triggered.
=> ci: avoid reporting if no need to run

.ci/scripts/test.sh
Our CI has been failing for a few weeks now.
The problem was a breaking change introduced by a python library named requests, specifically in version 2.32.0.
Please, see more details here: https://github.com/docker/docker-py/issues/3256
I've pinned the [requests](https://pypi.org/project/requests/) dependency version to 2.31.0 as suggested in multiple discussions associated with the issue linked above
=> chore: pin python requests dependency version

.github/workflows/pre-release.yml, .github/workflows/release.yml
Use GitHub secrets for running the release and sending slack notifications.
These secrets are now managed through IasC.
=> ci: use github secrets for GH token and Slack bot

.github/workflows/ci-saucelabs.yml, .github/workflows/run-test/action.yml
Remove access to Vault to gather the Saucelab credentials and use GitHub secrets
- Can the env variables `SAUCE_USERNAME` and `SAUCE_ACCESS_KEY` be defined with empty values?
=> ci: use github secrets for saucelabs

packages/rum-core/src/common/observers/page-clicks.js, packages/rum-core/test/common/observers/page-clicks.spec.js
Resolves #1510 
We stop using [dataset](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset) (even in browsers where it works) and we use [getAttribute](https://developer.mozilla.org/en-US/docs/Web/API/Element/getAttribute)
Since we are modifying this area, we also take the opportunity to fix this other [issue](https://github.com/elastic/apm-agent-rum-js/pull/1452) that was reported a while ago
=> fix(rum): make sure custom transaction name logic is IE11 compliant

packages/rum-angular/CHANGELOG.md, packages/rum-angular/package.json, packages/rum-core/CHANGELOG.md, packages/rum-core/package.json, packages/rum-react/CHANGELOG.md, packages/rum-react/package.json, packages/rum-vue/CHANGELOG.md, packages/rum-vue/package.json, packages/rum/CHANGELOG.md, packages/rum/package.json, packages/rum/src/apm-base.js
- @elastic/apm-rum-angular@3.0.4
- @elastic/apm-rum-core@5.21.1
- @elastic/apm-rum-react@2.0.3
- @elastic/apm-rum-vue@2.1.7
- @elastic/apm-rum@5.16.1
=> chore(release): publish

scripts/ci-post-release.mjs
The post-release step relied on the core component to be tagged already, if that was not the case then the post-release will fail with:
```
Get sha commit for @elastic/apm-rum-core@5.21.1
fatal: ambiguous argument '@elastic/apm-rum-core@5.21.1': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
To avoid the chicken/egg, it's gonna try to detect the commit for the core tag, otherwise, it will tag the core with the current workspace commit.
Oriignal implementation -> https://github.com/elastic/apm-agent-rum-js/pull/1479
=> ci: fix the post-release and tag if core no tagged

.github/workflows/release.yml
Similarly done in https://github.com/elastic/apm-agent-nodejs/pull/4129 and https://github.com/elastic/elastic-otel-node/pull/249 
Remove the usage of Vault secrets for the NPMJS release
=> ci: use github secrets

docs/agent-api.asciidoc, docs/intro.asciidoc, docs/set-up.asciidoc, docs/sourcemap.asciidoc, docs/transaction-api.asciidoc, docs/upgrading.asciidoc
Closes https://github.com/elastic/observability-docs/issues/3724
Updates links to the APM guide to point to the Observability guide instead. Most links have redirects, but there was an exception found in https://github.com/elastic/observability-docs/issues/3724. To be safe, I updated all instances or `{apm-guide-ref}`.
=> docs: Update APM guide links to Observability guide links

docs/agent-api.asciidoc, docs/intro.asciidoc, docs/set-up.asciidoc, docs/sourcemap.asciidoc, docs/transaction-api.asciidoc, docs/upgrading.asciidoc
Backports https://github.com/elastic/apm-agent-rum-js/pull/1528 to 5.x
=> docs: Update APM guide links to Observability guide links (#1528)

.github/workflows/release.yml
This sets up keyless authentication to GCP with OIDC.
I have a successful dry-run here: https://github.com/elastic/apm-agent-rum-js/actions/runs/10850931893, which is deploying to a test bucket in the elastic-observability-ci GCP project
=> ci: set up OIDC in the release workflow

.github/workflows/pre-release.yml, .github/workflows/release.yml
Use the GitHub app to generate the required ephemeral tokens with the least permissive principle.
* Finer-grained tokens with Service Machine accounts are required to rotate the secrets manually.
* GitHub app to generate temporary tokens is the advanced approach to avoid the above
* Document what the GH workflow requires to run in terms of access
* GitHub Token with Permissions does not trigger GitHub builds 
Use `tibdex/github-app-token` with the required permissions and the repository scope
Remove the `permissions` configuration in the GH workflow.
Configure git checkout with the ephemeral token
Configure the GH_TOKEN with the ephemeral token
=> ci: use GitHub app for ephemeral tokens

.github/workflows/ci-saucelabs.yml, .github/workflows/ci.yml
⚠️ This PR was created by an automated tool. Please review the changes carefully. ⚠️ 
NOTE: https://github.com/elastic/apm-pipeline-library has been archived in favor of 
https://github.com/elastic/oblt-actions.
Requires https://github.com/elastic/oblt-actions/pull/16 to be merged.
If there are any questions, please reach out to the @elastic/observablt-ci
=> github-action: use elastic/oblt-actions/check-dependent-jobs

docs/intro.asciidoc
Backports https://github.com/elastic/apm-agent-rum-js/pull/1557 to 5.x
=> [5.x] [docs] Add a note about Elastic Cloud Serverless support

docs/configuration.asciidoc, packages/rum-core/src/common/compress.js, packages/rum-core/src/common/config-service.js, packages/rum-core/src/performance-monitoring/navigation/capture-navigation.js, packages/rum-core/src/performance-monitoring/performance-monitoring.js, packages/rum-core/src/performance-monitoring/transaction-service.js, packages/rum-core/test/common/apm-server.spec.js, packages/rum-core/test/performance-monitoring/transaction-service.spec.js
Reviving https://github.com/elastic/apm-agent-rum-js/pull/1187:
> # Context
> One of the requirements for [Crosslinking Synthetics with APM](https://github.com/elastic/synthetics/issues/265) issue was to allow the RUM agent the creation of the `page-load` transaction as child of the one created in Synthetics.
> 
> The main goal of that is to provide visibility into how the synthetic journeys are executed and what actions are happening inside every step. This [image](https://user-images.githubusercontent.com/3902525/116486823-ccd0f200-a88e-11eb-95da-527940a74081.png) extracted from the issue linked above it's a great example.
> 
> # Summary
> We expose a new [agent configuration](https://www.elastic.co/guide/en/apm/agent/rum-js/current/configuration.html) option named `pageLoadParentId` …
=> feat: add pageLoadParentId configuration

.github/workflows/ci.yml, .github/workflows/release.yml
According to https://github.com/actions/runner-images/issues/10636, it's not using ubuntu-22 but ubuntu-24
Therefore, the release is not working anymore and it fails with
```
npm error code 127
npm error path /home/runner/work/apm-agent-rum-js/apm-agent-rum-js/node_modules/fibers
npm error command failed
npm error command sh -c node build.js || nodejs build.js
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@5.1.1
npm error gyp info using node@18.20.5 | linux | x64
npm error gyp info find Python using Python version 3.12.3 found at "/usr/bin/python"
npm error gyp http GET https://nodejs.org/download/release/v18.20.5/node-v18.20.5-headers.tar.gz
npm error gyp http 200 https://nodejs.org/download/release/v18.20.5/node-v18.20.5-headers.tar.gz
npm error gyp …
```
=> ci: use python:3.10 and run npm ci on PRs

.ci/scripts/benchmarks.sh, .ci/scripts/load-testing.sh
current bare-metals are configured with docker-compose instead of docker compose
See 
vs
=> ci(benchmarks): use docker compose v1

.github/workflows/release.yml
Fixes
```
Git User: username=obltmachine, email=obltmachine@users.noreply.github.com
Running in prod mode
The 'GITHUB_TOKEN' env var isn't defined
```
=> ci(release): create GH_TOKEN for the releases

.github/workflows/pre-release.yml
Similarly done in https://github.com/elastic/apm-agent-rum-js/pull/1560
=> ci(pre-release): pin python version

scripts/ci-pre-release.mjs
```
lerna success version finished
remote: 
remote: Create a pull request for 'release/5.16.1-next' on GitHub by visiting:        
remote:      https://github.com/elastic/apm-agent-rum-js/pull/new/release/5.16.1-next        
remote: 
To https://github.com/elastic/apm-agent-rum-js
* [new branch]      release/5.16.1-next -> release/5.16.1-next
Warning: 1 uncommitted change
Failed to create GitHub PR
aborted: you must first push the current branch to a remote, or use the --head flag
```
but the branch is already pushed and `--head` is defaulted to the current branch...
```
-H, --head branch          The branch that contains commits for your pull request (default [current branch])
```
Let's try to use the explicit flag just in case that's the reason for the failure
and also change the branch …
=> ci: add head branch

docs/reference/index.md
Related to https://github.com/elastic/docs-content/pull/914
Removes reliance on temporary redirects in the docs-content repo.
=> [docs] Remove reliance on temporary redirects

docs/reference/agent-api.md, packages/rum-core/src/error-logging/error-logging.js, packages/rum-core/test/error-logging/error-logging.spec.js, packages/rum/src/apm-base.js, packages/rum/src/index.d.ts, packages/rum/test/specs/index.spec.js
Closes https://github.com/elastic/apm-agent-rum-js/issues/1591
This PR allows adding labels to the captureError function, similar to what we have in Node.js agent:
https://www.elastic.co/guide/en/apm/agent/nodejs/current/agent-api.html#apm-capture-error
Example usage:
```
apm.captureError(error, {
labels: {
errorType: 'ToastError',
},
});
```
=> feat: add support for adding labels to captured errors

docs/release-notes/index.md
Adding a new entry in the release notes docs for the upcoming release of the new version of the rum agent (v5.17.0). This new release includes the feature implemented in #1594
=> chore: update docs

docs/reference/supported-technologies.md
Fixes image paths to work with docs-assembler.
Notes for the reviewer:
* I was not able to get images in reference, extend, or release-notes to work using the `:::{image}` syntax because it seems to resolve differently than the Markdown `![]()` syntax. We should address this in docs-builder, but in order to get images working as soon as possible, I've used Markdown syntax and left us a `TO DO` in a code comment to add back the `screenshot` class where applicable.
=> [docs] Fix image paths for docs-assembler

docs/set-up.asciidoc
Backport https://github.com/elastic/apm-agent-rum-js/pull/1612 to 4.x
=> docs: update agent install instructions

.github/workflows/ci-saucelabs.yml
As discussed we're going to run tests on demand. The workflow can still be triggered manually. We should check other alternatives to test in real devices
=> chore: disable SauceLabs on PRs and push to main

.github/workflows/run-test/action.yml
Update GH workflows and actions to fix the run-shell-injection vulnerability.
More info: https://semgrep.dev/r?q=yaml.github-actions.security.run-shell-injection.run-shell-injection
Tested in personal fork: https://github.com/oakrizan/apm-agent-rum-js/actions/runs/16774497902/job/47497235763?pr=1
=> ci: fix semgrep reported run-shell-injection
