elastic/apm-agent-rum-js

- docs/sourcemap.asciidoc
> chore(docs): add git commit hash to sourcemap doc

- package.json
- src/apm-base.js
- src/bootstrap.js
- test/e2e/common/data.json
- test/e2e/general-usecase/app.e2e-spec.js
- test/e2e/general-usecase/app.js
- test/e2e/general-usecase/index.html
- test/e2e/manual-timing/app.js
- test/specs/apm-base.spec.js
* update to elastic-apm-js-core v0.8.0
> feat: instrument XHR

- docs/distributed-tracing-guide.asciidoc
A few suggested changes to the distributed tracing docs. Mostly grammar, and added a little more context to the opening paragraph. 
I think we'll also need to talk about layout and where this page is located within the RUM documentation, but we'll do that when I have more time to work on a restructure.
> docs: update distributed tracing

- package-lock.json
- package.json
- test/e2e/e2e.js
- test/e2e/standalone-html/app.e2e-spec.js
- test/e2e/standalone-html/index.html
> chore: update js-core to v2.1.1

- docs/index.asciidoc
- docs/intro.asciidoc
- docs/sourcemap.asciidoc
Versions master branch doc links to APM Server v6.5 per https://github.com/elastic/apm/issues/19
> docs: version cross doc links

- docs/advanced-topics.asciidoc
- docs/api.asciidoc
- docs/configuration.asciidoc
- docs/custom-transaction-name.asciidoc
- docs/custom-transactions.asciidoc
- docs/index.asciidoc
Closes elastic/apm-agent-js-base#58
@jahtalab - Here's a rough draft of what I'm thinking for this guide. It's written in more of a "blog post" style vs. "documentation" style. I'd like to hear your thoughts on layout, and have you do a technical edit to ensure I'm using the right terminology. 
Note: I changed up the structure of the RUM docs a little bit to make way for this.
> Docs: Guide to setting initial page load transaction name

- docs/index.asciidoc
- docs/supported-technologies.asciidoc
+ fixes elastic/apm-agent-js-base#52
> docs: add supported technolgies page

- .eslintrc.js
- package-lock.json
- package.json
- src/opentracing-entry.js
- src/opentracing/index.js
- test/e2e/general-usecase/app.e2e-spec.js
- test/e2e/general-usecase/app.js
- test/e2e/standalone-html/app.e2e-spec.js
- test/e2e/standalone-html/index.html
- test/e2e/standalone-html/opentracing.html
- test/specs/apm-base.spec.js
- webpack.config.js
add a separate bundle for opentracing
minor fixes
Requires https://github.com/elastic/apm-agent-js-core/pull/23 to be released!
> feat: add OpenTracing support

- package-lock.json
- package.json
- scripts/license-checker.js
> chore: add license checker during linting phase

- docs/api.asciidoc
- docs/redirects.asciidoc
- src/apm-base.js
- test/e2e/general-usecase/app.js
- test/specs/index.spec.js
+ corresponding PR in core https://github.com/elastic/apm-agent-js-core/pull/28
> docs: remove setTags in favor of addTags

- docs/api.asciidoc
+ Docs update of elastic/apm-agent-js-base#88 
+ depends on https://github.com/elastic/apm-agent-js-core/pull/34
> docs: update on span tag keys and transaction marks

- .eslintrc.js
- dev-utils/karma.js
- dev-utils/test.js
- packages/rum-core/karma.bench.conf.js
- packages/rum-core/src/common/apm-server.js
- packages/rum-core/src/common/patching/fetch-patch.js
- packages/rum-core/src/common/patching/xhr-patch.js
- packages/rum-core/src/error-logging/error-logging.js
- packages/rum-core/src/error-logging/index.js
- packages/rum-core/src/index.js
- packages/rum-core/src/performance-monitoring/index.js
- packages/rum-core/src/performance-monitoring/performance-monitoring.js
- packages/rum-core/test/common/config-service.spec.js
- packages/rum-core/test/common/throttle.spec.js
- packages/rum-core/test/common/utils.spec.js
- packages/rum-core/test/index.js
- packages/rum-core/test/utils/apm-server-mock.js
- packages/rum-core/test/utils/transportMock.js
- packages/rum/run-script.js
- packages/rum/src/index.js
- packages/rum/test/e2e/integration-test.js
- packages/rum/test/e2e/sourcemap/test-sourcemap.js
- packages/rum/test/node/upload-sourcemaps.node-spec.js
- packages/rum/wdio.conf.js
- test.config.js
+ part of elastic/apm-agent-js-base#146
> chore: use object shorthand notation in eslint rules

- .travis.yml
- package.json
- scripts/export-saucelabs-account
- scripts/sauce-unit-test.sh
- scripts/sauce_unit_test.sh
> chore: split travis jobs

- README.md
- RELEASE.md
- dev-utils/publish.js
- lerna.json
- package.json
- scripts/publish.js
+ Publish individual packages via Lerna 
+ `release.md` which contains information on publishing
> chore: publish individual packages via lerna

- CONTRIBUTING.md
+ Added dev, test and lint section to contributing docs.
> docs: add more workflow sections to contributing.md

- packages/rum-core/package.json
- packages/rum/package.json
+ check this https://github.com/npm/rfcs/blob/latest/implemented/0010-monorepo-subdirectory-declaration.md for explanation.
> chore: add repository.directory field to package.json[skip ci]

- package-lock.json
- package.json
- packages/rum-core/src/common/patching/fetch-patch.js
- packages/rum-core/src/performance-monitoring/performance-monitoring.js
- packages/rum-core/src/performance-monitoring/transaction-service.js
- packages/rum-core/src/performance-monitoring/transaction.js
- packages/rum-core/test/common/fetch-patch.spec.js
- packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
- packages/rum-core/test/performance-monitoring/transaction.spec.js
- packages/rum/test/e2e/.babelrc.js
- packages/rum/test/e2e/react/app.e2e-spec.js
- packages/rum/test/e2e/react/app.jsx
- packages/rum/test/e2e/react/index.html
- packages/rum/test/e2e/react/main-component.jsx
- packages/rum/test/e2e/react/rum.js
- packages/rum/test/e2e/react/webpack.config.js
closes elastic/apm-agent-js-base#101
> feat(rum-core): Add task API

- .travis.yml
- CONTRIBUTING.md
- RELEASE.md
- dev-utils/karma.js
- docs/api.asciidoc
- docs/custom-transactions.asciidoc
- docs/intro.asciidoc
- docs/opentracing.asciidoc
- docs/sourcemap.asciidoc
- package-lock.json
- package.json
- packages/rum-core/NOTICE.txt
- packages/rum-core/package.json
- packages/rum/NOTICE.txt
- packages/rum/package.json
- packages/rum/src/bootstrap.js
- packages/rum/src/index.js
- packages/rum/src/opentracing-entry.js
- packages/rum/src/opentracing/index.js
- packages/rum/test/e2e/bundle-test/index.html
- packages/rum/test/e2e/standalone-html/index.html
- packages/rum/test/specs/apm-base.spec.js
- packages/rum/test/specs/index.spec.js
- packages/rum/webpack.config.js
- scripts/export-saucelabs-account
Rename npm packages to use elastic org
Fix documentation with regards to package name change
> BREAKING CHANGE: Rename the final JS bundles

- packages/rum/src/apm-base.js
- packages/rum/test/e2e/general-usecase/app.e2e-spec.js
> fix(rum): keep page load transaction until load

- packages/rum-core/src/performance-monitoring/capture-hard-navigation.js
- packages/rum-core/test/performance-monitoring/capture-hard-navigation.spec.js
> fix(rum-core): fix custom marks for page-load

- docs/agent-api.asciidoc
- packages/rum-core/src/common/apm-server.js
- packages/rum-core/src/common/config-service.js
- packages/rum-core/src/common/service-factory.js
- packages/rum-core/src/performance-monitoring/performance-monitoring.js
- packages/rum-core/src/performance-monitoring/transaction-service.js
- packages/rum-core/test/common/apm-server.spec.js
- packages/rum-core/test/common/config-service.spec.js
- packages/rum/src/apm-base.js
- packages/rum/test/specs/apm-base.spec.js
+ fix elastic/apm-agent-rum-js#210 
+ Extracted from elastic/apm-agent-rum-js#216 
+ Refactored few methods to reduce the code size.
> fix(rum): return noop agent when config is inactive

- docs/sourcemap.asciidoc
Compliments https://github.com/elastic/apm-server/pull/2090, and closes https://github.com/elastic/apm-server/issues/2087.
> [docs] Update source map documentation

- docs/agent-api.asciidoc
- docs/transaction-api.asciidoc
> docs: link to metadata section

- docs/configuration.asciidoc
~**Do not merge yet. Blocked by: https://github.com/elastic/kibana/pull/38577**~
Implements https://github.com/elastic/apm/issues/81
> [docs][7.2] update environment config

- packages/rum-core/src/common/url.js
- packages/rum-core/src/common/utils.js
- packages/rum-core/src/performance-monitoring/performance-monitoring.js
- packages/rum-core/test/common/url.spec.js
- packages/rum-core/test/common/utils.spec.js
- packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
+ fixes elastic/apm-agent-rum-js#252 
+ Removes the username:password fields from URL on XHR calls
> fix(rum-core): remove sensitive info from span context

- packages/rum-core/src/common/apm-server.js
- packages/rum-core/src/common/config-service.js
- packages/rum-core/src/error-logging/error-logging.js
- packages/rum-core/test/common/apm-server.spec.js
- packages/rum-core/test/common/config-service.spec.js
- packages/rum-core/test/common/utils.spec.js
- packages/rum-core/test/error-logging/error-logging.spec.js
- packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
- packages/rum/src/apm-base.js
- packages/rum/test/specs/apm-base.spec.js
- packages/rum/test/specs/index.spec.js
+ fixes elastic/apm-agent-rum-js#86 #248 #247 
+ Logs error on invalid configs
+ Improved the error message to help the users find problem
+ Included the fix for removing trailing slash on serverUrl
> feat(rum): better log message on invalid configuration

- dev-utils/test-config.js
- packages/rum-core/test/common/fetch-patch.spec.js
- packages/rum-core/test/common/xhr-patch.spec.js
+ test to figure out if DT works as expected in latest browsers.
> chore: add chrome 74 to e2e test

- package-lock.json
- package.json
+ fix security vulnerability with `lodash.template`
> chore(deps): upgrade lerna and fix lodash.template vulnerability

- docs/react-integration.asciidoc
- package-lock.json
- package.json
- packages/rum-react/src/get-apm-route.js
- packages/rum-react/src/get-with-transaction.js
- packages/rum-react/test/e2e/react/app.jsx
- packages/rum-react/test/specs/get-apm-route.spec.js
- packages/rum-react/test/specs/get-with-transaction.spec.js
- scripts/license-checker.js
Add doc note about Route.render usage
Add ApmRoute tests and improve code coverage
> fix(rum-react): check component in withTransaction

- codecov.yml
+ fix elastic/apm-agent-rum-js#333 
+ do not wait for whole CI to pass before the generating the report. 
+ fix file paths of the report.
> chore(codecov): fix coverage report issues

- packages/rum-core/src/common/apm-server.js
- packages/rum-core/test/common/apm-server.spec.js
- packages/rum-core/test/common/fetch-patch.spec.js
> feat(rum-core): improver error message on payload failure

- packages/rum-core/src/common/constants.js
+ part of #341 
+ Interim fix to remove blank duration in the transaction
> fix(rum-react): reduce transaction reusability threshold to 5 seconds

- packages/rum-core/src/performance-monitoring/performance-monitoring.js
- packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
> feat(rum-core): provide debug logs when transaction was discarded

- dev-utils/build.js
- packages/rum-react/babel.config.js
- packages/rum-react/package.json
+ should be merged after elastic/apm-agent-rum-js#355 
+ fixes elastic/apm-agent-rum-js#352
> feat(rum-react): publish traspiled react elements as es modules

- docs/configuration.asciidoc
- packages/rum-core/src/common/config-service.js
- packages/rum-core/src/common/constants.js
- packages/rum-core/src/common/instrument.js
- packages/rum-core/src/common/patching/fetch-patch.js
- packages/rum-core/src/common/patching/history-patch.js
- packages/rum-core/src/common/patching/index.js
- packages/rum-core/src/common/patching/xhr-patch.js
- packages/rum-core/src/common/service-factory.js
- packages/rum-core/src/index.js
- packages/rum-core/src/performance-monitoring/performance-monitoring.js
- packages/rum-core/src/performance-monitoring/transaction-service.js
- packages/rum-core/test/common/fetch-patch.spec.js
- packages/rum-core/test/common/history-patch.spec.js
- packages/rum-core/test/common/instrument.spec.js
- packages/rum-core/test/common/xhr-patch.spec.js
- packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
- packages/rum-core/test/performance-monitoring/transaction-service.spec.js
- packages/rum/src/apm-base.js
- packages/rum/test/specs/apm-base.spec.js
+ fixes elastic/apm-agent-rum-js#192 
+ Constants fields for different sources are normalized and matches with events to avoid bloating the code.  
+ Separated the tasks in to individual events for AJAX, Fetch and History calls.
> feat(rum):add instrument flag to toggle instrumentations

- packages/rum/src/apm-base.js
+ missed it during publishing.
> fix(rum): sync version number with latest published version

- package-lock.json
- package.json
+ fix npm audit errors and github security warnings.
> chore(security): fix npm audit and github security warnings

- packages/rum/src/apm-base.js
+ fix duplicate import statements to `@elastic/apm-rum-core`
> chore(rum): merge duplicate import statementments in apm base

- docs/angular-integration.asciidoc
- docs/framework-integrations.asciidoc
- docs/supported-technologies.asciidoc
+ part of elastic/apm-agent-rum-js#292
> docs(angular): add angular framework integration document

- packages/rum-angular/src/apm-service.ts
- packages/rum-angular/test/specs/apm-service.spec.ts
+ fixes elastic/apm-agent-rum-js#413 
+ We traverse the activated router tree using DFS and construct the path along the way eliminating the parent path names which is set to empty string. `firstChild` always reflects the current activated route.
> fix(rum-angular): proper transaction name for lazy loaded routes

- docs/sourcemap.asciidoc
For https://github.com/elastic/apm-server/pull/2728. Must be merged at the same time.
> docs: update moved secret token link

- packages/rum-core/src/error-logging/error-logging.js
- packages/rum-core/test/error-logging/error-logging.spec.js
+ fixes elastic/apm-agent-rum-js#309
> feat(rum-core): copy transaction context info to error

- docs/configuration.asciidoc
part of elastic/apm-agent-rum-js#253
> docs: Add Central Config documentation

- docs/agent-api.asciidoc
> docs: add managed option to startTransaction

- docs/breakdown-metrics.asciidoc
- docs/configuration.asciidoc
- docs/index.asciidoc
- docs/supported-technologies.asciidoc
+ part of elastic/apm-agent-rum-js#289
> docs: detailed breakdown metrics and config flag [skip ci]

- docs/framework-integrations.asciidoc
- docs/vue-integration.asciidoc
+ part of elastic/apm-agent-rum-js#460
> docs: add vue package integration docs [skip ci]

- packages/rum-core/src/common/logging-service.js
- packages/rum-core/src/common/service-factory.js
- packages/rum-core/src/performance-monitoring/performance-monitoring.js
- packages/rum-core/src/performance-monitoring/transaction-service.js
- packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
- packages/rum/src/apm-base.js
- packages/rum/src/bootstrap.js
- packages/rum/test/specs/apm-base.spec.js
- packages/rum/test/specs/index.spec.js
+ fixes elastic/apm-agent-rum-js#452 
+ Annotates the debug logs with transaction name and type on each log
+ Prefix the log with `[Elastic APM] `  for grouping on the console. 
Looks like below image on the console.
> feat(rum-core): improve the debug logs with transaction details

- docs/agent-api.asciidoc
> docs: agent API observe plus transaction events [skip ci]

- packages/rum-core/src/common/patching/xhr-patch.js
- packages/rum-core/src/common/utils.js
- packages/rum-core/src/index.js
- packages/rum-core/test/common/xhr-patch.spec.js
- packages/rum-core/test/index.js
- packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
- packages/rum-vue/src/route-hooks.js
- packages/rum/test/specs/apm-base.spec.js
* fixes elastic/apm-agent-rum-js#390
* cleanups in the tests
> fix: schedule xhr invoke task as a macro task

- package-lock.json
- packages/rum-angular/NOTICE.txt
- packages/rum-angular/package.json
- packages/rum-angular/src/apm-service.ts
+ Use the new utility to be consistent with vue integration
+ update notice for the angular package.
> refactor(rum-angular): use schedule microtask util from rum-core

- packages/rum-core/src/common/constants.js
- packages/rum-core/src/performance-monitoring/performance-monitoring.js
- packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
- packages/rum/test/e2e/manual-timing/app.js
- packages/rum/test/specs/apm-base.spec.js
> feat: capture http-request transactions

- scripts/build_docs.sh
Updates the doc build script. See https://github.com/elastic/docs/pull/1634.
> [docs] Update build script

- packages/rum/src/apm-base.js
- packages/rum/test/specs/apm-base.spec.js
+ Found this unused method while doing Typescript definition and also used API method internally.
> chore(rum): clean up public API and use API methods

- packages/rum-core/src/performance-monitoring/performance-monitoring.js
- packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
> feat: send transactions with no spans

- docs/intro.asciidoc
- docs/supported-technologies.asciidoc
+ fix #474 
+ Took the liberty to enhance the page load transaction instrumentation with additional navigation timing spans that were missing before.
> docs: improve the page laod transaction instrumentation [skip ci]

- package-lock.json
+ fix for https://github.com/elastic/apm-agent-rum-js/pull/550
> chore: bump handlebars to fix security vulnerability

- packages/rum-vue/test/specs/index.spec.js
+ Improve the test coverage of vue by testing the navigation error and optional router which we recently introduced.
> chore(rum-vue): improve vue integration test coverage

- .eslintrc.js
- dev-utils/karma.js
- docs/advanced-topics.asciidoc
- packages/rum/package.json
- packages/rum/src/index.d.ts
- packages/rum/test/types/index.spec.ts
- packages/rum/test/types/tsconfig.json
+ related: elastic/apm-agent-rum-js#70 
+ Added tests for the types which would error out if the API is used improperly.
> feat(rum): add typescript typings

- packages/rum/src/index.d.ts
- packages/rum/test/benchmarks/BENCHMARKS.md
- packages/rum/test/types/index.spec.ts
+ missed this while providing the typings for ApmBase
> fix(rum): add constructor types for ApmBase class

- packages/rum/test/benchmarks/BENCHMARKS.md
> docs(rum): Benchmark metrics explanation doc

- packages/rum/src/apm-base.js
- packages/rum/test/specs/apm-base.spec.js
+ fix elastic/apm-agent-rum-js#566
> fix(rum): noop for API when agent is inactive

- packages/rum-core/test/performance-monitoring/transaction-service.spec.js
> chore(rum-core): run all tests in karma

- packages/rum-core/src/error-logging/error-logging.js
- packages/rum-core/test/error-logging/error-logging.spec.js
+ fix https://github.com/elastic/apm-agent-rum-js/issues/582, https://github.com/elastic/apm-agent-rum-js/issues/580
> fix(rum-core): add error properties to custom context by default

- dev-utils/integration-test.js
testing it on ITs I realized that the condition is inverted
> ci: ignoreHTTPSErrors check condition is inverted

- docs/sourcemap.asciidoc
Backports https://github.com/elastic/apm-agent-rum-js/pull/611
> docs: Fix release build (#611)

- docs/configuration.asciidoc
- docs/supported-technologies.asciidoc
> docs: document user interactions

- packages/rum-core/src/common/apm-server.js
- packages/rum-core/test/common/apm-server.spec.js
> feat: add labels config to metadata payload

- packages/rum-core/src/performance-monitoring/performance-monitoring.js
- packages/rum-core/test/common/apm-server.spec.js
- packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
> chore(rum-core): remove test util function from performance monitoring

- dev-utils/jasmine.js
- package-lock.json
- package.json
- packages/rum-core/test/common/apm-server.spec.js
- packages/rum-core/test/common/event-target-patch.spec.js
- packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
> chore(tests): review tests and add utils

- dev-utils/karma.js
- package-lock.json
- package.json
+ Our unit test are broken in Travis right now. 
+ removed unused firefox launcher
> chore(karma): fix karma tests in travis

- Jenkinsfile
All a post step to all stages that run unit tests.
Fix a bug introduced on https://github.com/elastic/apm-agent-rum-js/pull/542
Closes https://github.com/elastic/apm-agent-rum-js/issues/672
> ci: collect JUnit results

- docs/configuration.asciidoc
Fixes: #675
Fix disabling user-interaction
> docs: add notes on disableInstrumentations values

- .ci/docker/node-playwright/Dockerfile
- dev-utils/docker-compose.yml
- package-lock.json
- package.json
- packages/rum/test/benchmarks/config.js
+ Uses the image configuration from Playwright https://github.com/microsoft/playwright/blob/master/docs/docker/Dockerfile.bionic
+ Added some extra package/steps to make it work for both our karma and playwright benchmarks.
> chore(benchmarks): run benchmarks in firefox and fix docker image

- lerna.json
- packages/rum-core/test/performance-monitoring/capture-navigation.spec.js
- scripts/github-release.js
Fixes #687
* fix changelog url
* Some cleanups
@vigneshshanmugam , Please let me know if you think any other changes are necessary for releasing from 4.x branch.
> chore:  lerna version add 4.x to allowed branches

- packages/rum-core/src/performance-monitoring/performance-monitoring.js
- packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
- packages/rum/test/e2e/general-usecase/app.e2e-spec.js
> fix(rum-core): replace >> in click transaction name with '-'

- packages/rum-angular/test/e2e/with-router/app/app.module.ts
- packages/rum-core/src/common/config-service.js
- packages/rum-core/src/common/service-factory.js
- packages/rum-core/test/common/config-service.spec.js
- packages/rum-core/test/common/service-factory.spec.js
- packages/rum-react/test/e2e/with-router/general.js
- packages/rum-react/test/e2e/with-router/switch.js
- packages/rum-vue/test/e2e/app.js
- packages/rum/test/e2e/general-usecase/app.js
> BREAKING CHANGE(rum-core): remove debug config in favor of logLevel

- packages/rum-core/src/performance-monitoring/span-base.js
- packages/rum/src/apm-base.js
> BREAKING CHANGE: remove addTags method

- packages/rum-core/src/common/context.js
- packages/rum-core/src/common/truncate.js
- packages/rum-core/src/error-logging/error-logging.js
- packages/rum-core/test/common/context.spec.js
- packages/rum-core/test/common/truncate.spec.js
- packages/rum-core/test/error-logging/error-logging.spec.js
Fixes #618 
instead we rely on metadata labels
> BREAKING CHANGE: tags are not added to individual events

- package-lock.json
- package.json
+ fix security vulnerability warnings.
> chore(deps): upgrade deps to fix audit warnings [skip ci]

- package-lock.json
- package.json
> chore(deps): remove unused deps and fix lockfile

- Jenkinsfile
Reverts elastic/apm-agent-rum-js#659
> Revert "ci(jenkins): benchmark fails with playwright in the CI"

- Jenkinsfile
Closes https://github.com/elastic/apm-agent-rum-js/issues/726
> ci(jenkins): apm-its disabled when docs

- packages/rum-core/karma.bench.conf.js
- packages/rum-core/test/benchmarks/breakdown.bench.js
- packages/rum-core/test/benchmarks/capture-navigation.bench.js
- packages/rum-core/test/benchmarks/index.js
- packages/rum-core/test/benchmarks/performance-monitoring.bench.js
- packages/rum-core/test/benchmarks/transaction-service.bench.js
> chore(benchmarks): more microbenchmarks to find hot path

- packages/rum-angular/package.json
+ missed from https://github.com/elastic/apm-agent-rum-js/pull/734/
> chore(rum-angular): add build step for es2015

- .travis.yml
- dev-utils/test-utils.js
+ Travis is run on Node 12 to be in sync with our Jenkins and also most libs are removing support for 8.
+ selenium code is removed now that we are using devtools protocol with webdriver for local testing.
> chore: update to node:12 in travis

- CHANGELOG.asciidoc
+ based on our recent release.
> docs: update release notes for 5.1.0

- packages/rum-core/src/performance-monitoring/capture-navigation.js
- packages/rum-core/src/performance-monitoring/perf-entry-recorder.js
- packages/rum-core/src/performance-monitoring/transaction-service.js
- packages/rum-core/test/fixtures/paint-entries.js
- packages/rum-core/test/performance-monitoring/capture-navigation.spec.js
- packages/rum-core/test/performance-monitoring/perf-entry-recorder.spec.js
- packages/rum-core/test/performance-monitoring/transaction-service.spec.js
- packages/rum-core/test/utils/globals-mock.js
> feat(rum-core): use performance observer to capture FCP

- packages/rum-angular/test/index.ts
- packages/rum-core/src/common/apm-server.js
- packages/rum-core/src/common/constants.js
- packages/rum-core/src/common/service-factory.js
- packages/rum-core/src/error-logging/index.js
- packages/rum-core/src/index.js
- packages/rum-core/src/performance-monitoring/index.js
- packages/rum-core/test/common/service-factory.spec.js
- packages/rum-react/test/e2e/index.js
- packages/rum-vue/test/e2e/index.js
- packages/rum/src/apm-base.js
- packages/rum/src/index.d.ts
- packages/rum/test/e2e/index.js
- packages/rum/test/types/index.spec.ts
Fixes #238
The gzipped bundle size is reduced from 16.78 KB on master to 16.65 KB.
> perf: refactor ServiceFactory to use constant service names

- docs/configuration.asciidoc
+ part of #768 
+ Docs for the config introduced as part of #771
> docs: add apiVersion configuration

- docs/index.asciidoc
- docs/performance-tuning.asciidoc
> docs: add performance tuning docs [skip ci]

- Jenkinsfile
7.7 version has been released recently
> ci: bump ES version (7.7.0)

- packages/rum-core/src/performance-monitoring/capture-navigation.js
- packages/rum-core/test/performance-monitoring/capture-navigation.spec.js
+ fix #818 
+ fix #817 
+ The agent would discard capturing transaction page load marks for buggy navigation timing data which posses issues when creating custom dashboards using the marks.
> fix(rum-core): protect against buggy navigation timing data

- CHANGELOG.asciidoc
+ Releases notes for https://github.com/elastic/apm-agent-rum-js/commit/91de44a75fd780f5dcd39fce60b028422a626a6c
> docs: release notes for 5.2.1

- CHANGELOG.asciidoc
+ Release notes for https://github.com/elastic/apm-agent-rum-js/releases/tag/%40elastic%2Fapm-rum%405.3.0
> docs: add release notes for 5.3.0

- CONTRIBUTING.md
Add info about pre-commit hook and enabling these.
Issue #835
> Update linting in Contributing Guide

- package-lock.json
- package.json
+ fix https://github.com/elastic/apm-agent-rum-js/network/alert/package-lock.json/codecov/open
> chore(deps): update codecov to fix security issues

- CHANGELOG.asciidoc
+ Releases notes for 5.4.0 published yesterday.
> docs: release notes for 5.4.0

- package-lock.json
- package.json
+ fix https://github.com/elastic/apm-agent-rum-js/network/alert/package-lock.json/elliptic/open
> chore(deps): bump webpack to update elliptic

- .ci/docker/node-playwright/Dockerfile
- .ci/scripts/benchmarks.sh
- package-lock.json
- package.json
- packages/rum/test/benchmarks/profiler.js
+ updates playwright to the latest version
+ fix deprecated methods, cache is disabled by default for every run in playwright itself.
> chore(benchmarks): update script to use new playwright API

- docs/intro.asciidoc
> docs: fix distributed tracing section

- package-lock.json
- package.json
+ fix the version mismatch when using saucelabs tests. 
+ More details - https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fapm-agent-rum-mbp/detail/PR-866/4/pipeline
> chore: fix sauce connect launcher version

- packages/rum-core/test/performance-monitoring/capture-navigation.spec.js
+ This issue is creating too many test failures in all of the PR's 
+ https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fapm-agent-rum-mbp/detail/PR-873/10/pipeline
> chore: fix broken test with transaction agent marks

- docs/agent-api.asciidoc
- docs/custom-transactions.asciidoc
- docs/transaction-api.asciidoc
+ Addressed changes from review https://github.com/elastic/apm-agent-rum-js/pull/866#pullrequestreview-469731683
> docs: address grammar suggestions

- .ci/docker/node-playwright/Dockerfile
- .ci/docker/node-puppeteer/Dockerfile
+ master build is broken. https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fapm-agent-rum-mbp/detail/master/318/pipeline
> chore: fix benchmark dependencies

- CHANGELOG.asciidoc
> docs: release notes for 5.6.0

- packages/rum-core/src/common/compress.js
- packages/rum-core/src/performance-monitoring/metrics.js
- packages/rum-core/src/performance-monitoring/transaction-service.js
- packages/rum-core/test/performance-monitoring/metrics.spec.js
- packages/rum-core/test/performance-monitoring/transaction-service.spec.js
> feat(rum-core): add longtask to experience field

- packages/rum-core/src/common/config-service.js
- packages/rum-core/test/common/apm-server.spec.js
- packages/rum-core/test/common/config-service.spec.js
> feat(rum-core): transactionSampleRate precision

- CHANGELOG.asciidoc
> docs: release notes for 5.6.2

- packages/rum/src/index.d.ts
Add eventtarget to the instrumentation types.
> chore(rum): add eventtarget to the instrumentation types

- packages/rum-angular/test/e2e/with-router/app.e2e-spec.js
- packages/rum-core/src/performance-monitoring/metrics.js
- packages/rum-core/test/performance-monitoring/metrics.spec.js
- packages/rum-core/test/performance-monitoring/performance-monitoring.spec.js
- packages/rum-vue/test/e2e/app.e2e-spec.js
> feat(rum-core): capture buffered longtask entries

- docs/configuration.asciidoc
- packages/rum-core/src/common/utils.js
- packages/rum-core/test/common/utils.spec.js
close #943 
I didn't test locally because of #972 and other things related to initialize dev env.
> feat(rum-core): support regex same origin

- .ci/packer_cache.sh
> ci: skip packer cache on ARM

- Jenkinsfile
As discussed in https://github.com/elastic/apm-agent-rum-js/pull/959#pullrequestreview-612293907
> ci: use the load testing index

- CHANGELOG.asciidoc
+ Release notes for https://github.com/elastic/apm-agent-rum-js/releases/tag/%40elastic%2Fapm-rum%405.7.1
> docs: release notes for 5.7.1

- docs/angular-integration.asciidoc
+ part of #962 
+ Overrides the previous integration document with the new changes.
> docs: update angular integration for >9 versions

- packages/rum-core/src/common/compress.js
- packages/rum-core/test/common/apm-server.spec.js
> fix(rum-core): mapping for marks were incorrect

- CHANGELOG.asciidoc
> docs: release notes for 5.7.2

- packages/rum/test/e2e/general-usecase/app.e2e-spec.js
- packages/rum/test/e2e/general-usecase/app.js
- scripts/apm-server-load-test.js
This PR adds e2e test for sessions. it also adds session to APM server load testing
Part of #634
> chore: add e2e test for sessions

- packages/rum-core/src/common/apm-server.js
- packages/rum-core/src/common/config-service.js
- packages/rum-core/test/common/apm-server.spec.js
- packages/rum/test/e2e/general-usecase/app.js
This PR adds apmServerRequest config to intercept requests to APM server.
Fixes #1018
> feat(rum-core): add apmServerRequest config

- docs/configuration.asciidoc
Provides documentation for #1018
> docs: document apmRequest config

- packages/rum/package.json
> chore: increase bundle size limit

- Jenkinsfile
[6.8.16, 7.13.0, 7.13.1, 7.13.2]
> chore: update elastic stack release version [7.13.2]

- CHANGELOG.asciidoc
> docs: add release notes for 5.9.0

- CHANGELOG.asciidoc
> docs: add release notes for 5.9.1

- docs/configuration.asciidoc
Closes https://github.com/elastic/apm-agent-rum-js/issues/1004.
> docs: Change `pageLoadSampled` to Boolean

- .ci/docker/node-playwright/Dockerfile
- package-lock.json
- package.json
+ Updates the latest set of deps from playwright install-deps command. 
+ fixes https://github.com/elastic/apm-agent-rum-js/issues/1072
+ fixes #1037
> chore: update latest deps for playwright image

- packages/rum/src/index.d.ts
- packages/rum/test/types/index.spec.ts
With this change the following types are going to be exposed:
- Transaction
- Span
- TransactionOptions
- SpanOptions
> feat(rum): export rum types (#1045)

- .ci/scripts/load-testing.sh
- .ci/scripts/pull_and_build.sh
- .ci/scripts/test.sh
- Jenkinsfile
- dev-utils/docker-compose.yml
> chore: update elastic stack release version 7.15.2 7.16.0

- CHANGELOG.asciidoc
> docs: add release notes for 5.10.0

- docs/vue-integration.asciidoc
+ Keeping it ready for the 2.x release of `@elastic/apm-rum-vue` package.
> docs: adjust vue intergration docs for 3.x

- packages/rum-core/src/performance-monitoring/metrics.js
- packages/rum-core/src/performance-monitoring/transaction-service.js
- packages/rum-core/src/state.js
- packages/rum-core/test/performance-monitoring/metrics.spec.js
+ fix #1033 
As per https://web.dev/evolving-cls/ this PR updates the way the RUM agent calculates the Cumulative Layout Shift metric.
The new technique used to calculate the metric is known as **max-session-gap1s-limit5s**
> feat(rum-core): update cls definition

- .ci/scripts/load-testing.sh
- .ci/scripts/pull_and_build.sh
- .ci/scripts/test.sh
- Jenkinsfile
- dev-utils/docker-compose.yml
> chore: update elastic stack release version 7.16.2 7.17.0

- CHANGELOG.asciidoc
> docs: add release notes for 5.10.1

- .ci/scripts/load-testing.sh
- .ci/scripts/pull_and_build.sh
- .ci/scripts/test.sh
- Jenkinsfile
- dev-utils/docker-compose.yml
> chore: update elastic stack release version 7.16.3 7.17.0

- CONTRIBUTING.md
- Jenkinsfile
- README.md
- RELEASE.md
- dev-utils/karma.js
- lerna.json
- packages/rum-core/src/common/utils.js
- scripts/lint-commits.sh
> chore: neutral naming for apm-agent-rum-js

- CHANGELOG.asciidoc
> docs: add release notes for 5.10.2

- .ci/scripts/load-testing.sh
- .ci/scripts/pull_and_build.sh
- .ci/scripts/test.sh
- Jenkinsfile
- dev-utils/docker-compose.yml
- dev-utils/elasticsearch/roles.yml
- dev-utils/elasticsearch/service_tokens
- dev-utils/elasticsearch/users
- dev-utils/elasticsearch/users_roles
- dev-utils/kibana/kibana.yml
- packages/rum-core/test/common/apm-server.spec.js
- packages/rum/test/integration/upload-sourcemaps.spec.js
> chore: update elastic stack release version 8.1.2 8.2.0

- CHANGELOG.asciidoc
> docs: add release notes for 5.11.0

- .ci/scripts/load-testing.sh
- .ci/scripts/pull_and_build.sh
- .ci/scripts/test.sh
- Jenkinsfile
- dev-utils/docker-compose.yml
> chore: update elastic stack release version 8.2.0 8.2.0

- docs/configuration.asciidoc
- docs/troubleshooting.asciidoc
- Update configuration and troubleshooting 5.x docs
> docs: update docs

- CHANGELOG.asciidoc
- Update 5.x with the release notes modifications for 5.11.1
> docs: update 5.11.1 release notes

- CHANGELOG.asciidoc
- Update release 5.11.0 notes for 5.x branch
> docs: amend release 5.11.0 notes

- .ci/scripts/load-testing.sh
- .ci/scripts/pull_and_build.sh
- .ci/scripts/test.sh
- Jenkinsfile
- dev-utils/docker-compose.yml
> chore: update elastic stack release version 8.3.1 8.3.1

- .ci/scripts/load-testing.sh
- .ci/scripts/pull_and_build.sh
- .ci/scripts/test.sh
- Jenkinsfile
- dev-utils/docker-compose.yml
> chore: update elastic stack release version 8.3.2 8.3.2

- .ci/scripts/load-testing.sh
- .ci/scripts/pull_and_build.sh
- .ci/scripts/test.sh
- Jenkinsfile
- dev-utils/docker-compose.yml
> chore: update elastic stack release version 8.3.3 8.3.3

- .ci/scripts/load-testing.sh
- .ci/scripts/pull_and_build.sh
- .ci/scripts/test.sh
- Jenkinsfile
- dev-utils/docker-compose.yml
> chore: update elastic stack release version 8.4.2 8.4.2

- Jenkinsfile
See https://github.com/elastic/apm-integration-testing/issues/1523
> ci: remove Integration Tests stage

- .ci/scripts/load-testing.sh
- .ci/scripts/pull_and_build.sh
- .ci/scripts/test.sh
- Jenkinsfile
- dev-utils/docker-compose.yml
> chore: update elastic stack release version 8.5.0 8.5.0

- package-lock.json
- package.json
resolves https://github.com/elastic/apm-agent-rum-js/security/dependabot/73
(https://github.com/elastic/apm-agent-rum-js/pull/1297/files#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519R33588)
> chore: update karma to latest

- .ci/scripts/load-testing.sh
- .ci/scripts/pull_and_build.sh
- .ci/scripts/test.sh
- Jenkinsfile
- dev-utils/docker-compose.yml
> chore: update elastic stack release version 8.5.1 8.5.1

- .ci/snapshoty.yml
- .gitignore
- Jenkinsfile
- package.json
- packages/rum/src/index.d.ts
Signed-off-by: Adrien Mannocci <adrien.mannocci@elastic.co>
* Add support for daily snapshots.
> chore: support publishing a snapshot build

- .ci/scripts/load-testing.sh
- .ci/scripts/pull_and_build.sh
- .ci/scripts/test.sh
- Jenkinsfile
- dev-utils/docker-compose.yml
> chore: update elastic stack release version 8.6.0 8.6.0

- .ci/scripts/load-testing.sh
- .ci/scripts/pull_and_build.sh
- .ci/scripts/test.sh
- Jenkinsfile
- dev-utils/docker-compose.yml
> chore: update elastic stack release version 8.6.1 8.6.1

- docs/configuration.asciidoc
- docs/supported-technologies.asciidoc
Update 5.x with the changes made in:
- https://github.com/elastic/apm-agent-rum-js/pull/1362
- https://github.com/elastic/apm-agent-rum-js/pull/1361
> docs: update 5.x docs

- .github/workflows/ci.yml
<Actions>
<action id="1f84d10335f789c06041a85a7b85e84a1abc5fabdfecbbfa4281d1c39871c7f8">
<summary>Update elastic stack version to 8.8.0</summary>
<details>
<summary>8.8.0</summary>
<pre>&#xA;Release published on the 2023-05-25 09:24:20 +0000 UTC at the url https://github.com/elastic/elasticsearch/releases/tag/v8.8.0&#xA;&#xA;Downloads: https://elastic.co/downloads/elasticsearch&#xA;Release notes: https://www.elastic.co/guide/en/elasticsearch/reference/8.8/release-notes-8.8.0.html</pre>
</details>
</details>
</action>
<action id="3fe224001eb5ff8c60949977cb5fc3c2bb2943b33a49c9e09515d221fcdd5fe5">
<details …
> [updatecli] Bump elastic stack version to 8.8.1

- .github/workflows/release.yml
Changes npm command in charge to release agent
> chore: reword ci release command

- lerna.json
- package.json
- packages/rum-angular/CHANGELOG.md
- packages/rum-angular/package.json
- packages/rum-core/CHANGELOG.md
- packages/rum-core/package.json
- packages/rum-react/CHANGELOG.md
- packages/rum-react/package.json
- packages/rum-vue/CHANGELOG.md
- packages/rum-vue/package.json
- packages/rum/CHANGELOG.md
- packages/rum/package.json
- packages/rum/src/apm-base.js
+ This is just for the time-being to make the releases work from different branch till we fix the CI.
> chore: allow publishing to npm from different branch

- .github/workflows/release.yml
* Correct input coerce
* https://docs.github.com/en/actions/learn-github-actions/expressions#operators
* The release process isn't working as expected.
> ci: correct coerce in release workflow

- CHANGELOG.asciidoc
- Release notes for 5.14.0
**PREVIEW**
> docs: update 5.14.0 release notes

- CHANGELOG.asciidoc
Update 5.x with the changes made in https://github.com/elastic/apm-agent-rum-js/pull/1408
> docs: update 5.x release notes

- docs/react-integration.asciidoc
Update 5.x with the changes made in https://github.com/elastic/apm-agent-rum-js/pull/1411
> docs: update 5.x react docs

- .github/workflows/ci.yml
- .github/workflows/microbenchmark.yml
<Actions>
<action id="785939ca1cce1f6d5e7877397ddbbf7d72628a2d8371ca2fe0e4884149b47b37">
<summary>Update elastic stack version to 8.9.1</summary>
<p>Updated to content &#34;&#39;8.9.1&#39;&#34; in file &#34;.github/workflows/ci.yml&#34;&#xA;</p>
<details>
<summary>8.9.1</summary>
<pre>&#xA;Release published on the 2023-08-17 14:16:27 +0000 UTC at the url https://github.com/elastic/elasticsearch/releases/tag/v8.9.1&#xA;&#xA;Downloads: https://elastic.co/downloads/elasticsearch&#xA;Release notes: https://www.elastic.co/guide/en/elasticsearch/reference/8.9/release-notes-8.9.1.html</pre>
</details>
</details>
<details …
> [updatecli] Bump elastic stack version to 8.9.1

- docs/troubleshooting.asciidoc
Add note on `Script error` messages in local development environments.
> docs: muted errors in local dev for cors JS requests

- .github/workflows/ci.yml
- .github/workflows/microbenchmark.yml
<Actions>
<action id="077f662e2e681c3bedfd94903a59befded32d344b683f6ba04284c5b5317d17f">
<summary>Update elastic stack version to 8.9.2</summary>
<p>1 file(s) updated with &#34;&#39;8.9.2&#39;&#34;:&#xA;&#x9;* .github/workflows/ci.yml&#xA;</p>
<details>
<summary>8.9.2</summary>
<pre>&#xA;Release published on the 2023-09-06 21:11:01 +0000 UTC at the url https://github.com/elastic/elasticsearch/releases/tag/v8.9.2&#xA;&#xA;Downloads: https://elastic.co/downloads/elasticsearch&#xA;Release notes: https://www.elastic.co/guide/en/elasticsearch/reference/8.9/release-notes-8.9.2.html</pre>
</details>
</details>
<details …
> [updatecli] Bump elastic stack version to 8.9.2

- .github/workflows/ci.yml
- .github/workflows/microbenchmark.yml
<Actions>
<action id="c819905fe8e7235ce82ff888b3db3c6d2b9c45b4443f20a20b4396c04360399f">
<summary>Update elastic stack version to 8.10.2</summary>
<p>1 file(s) updated with &#34;&#39;8.10.2&#39;&#34;:&#xA;&#x9;* .github/workflows/microbenchmark.yml&#xA;</p>
<details>
<summary>8.10.2</summary>
<pre>&#xA;Release published on the 2023-09-21 10:49:36 +0000 UTC at the url https://github.com/elastic/elasticsearch/releases/tag/v8.10.2&#xA;&#xA;Downloads: https://elastic.co/downloads/elasticsearch&#xA;Release notes: https://www.elastic.co/guide/en/elasticsearch/reference/8.10/release-notes-8.10.2.html</pre>
</details>
</details>
<details …
> [updatecli] Bump elastic stack version to 8.10.2

- CHANGELOG.asciidoc
- Release notes for 5.15.0
**PREVIEW**
> docs: update 5.15.0 release notes

- .github/workflows/ci.yml
- .github/workflows/microbenchmark.yml
<Actions>
<summary>Update elastic stack version to 8.10.4</summary>
<p>1 file(s) updated with &#34;&#39;8.10.4&#39;&#34;:&#xA;&#x9;* .github/workflows/ci.yml&#xA;</p>
<details>
<summary>8.10.4</summary>
<pre>&#xA;Release published on the 2023-10-17 11:49:01 +0000 UTC at the url https://github.com/elastic/elasticsearch/releases/tag/v8.10.4&#xA;&#xA;Downloads: https://elastic.co/downloads/elasticsearch&#xA;Release notes: https://www.elastic.co/guide/en/elasticsearch/reference/8.10/release-notes-8.10.4.html</pre>
</details>
</details>
<details …
> [updatecli] Bump elastic stack version to 8.10.4

- packages/rum-angular/CHANGELOG.md
- packages/rum-angular/package.json
- packages/rum-core/CHANGELOG.md
- packages/rum-core/package.json
- packages/rum-react/CHANGELOG.md
- packages/rum-react/package.json
- packages/rum-vue/CHANGELOG.md
- packages/rum-vue/package.json
- packages/rum/CHANGELOG.md
- packages/rum/package.json
- packages/rum/src/apm-base.js
- @elastic/apm-rum-angular@3.0.3
- @elastic/apm-rum-core@5.21.0
- @elastic/apm-rum-react@2.0.2
- @elastic/apm-rum-vue@2.1.6
- @elastic/apm-rum@5.16.0
> chore(release): publish

- CHANGELOG.asciidoc
- Release notes for 5.16.0
**PREVIEW**
> docs: update 5.16.0 release notes

- .github/workflows/ci.yml
- .github/workflows/microbenchmark.yml
<Actions>
<summary>Update elastic stack version to 8.11.0</summary>
<p>1 file(s) updated with &#34;&#39;8.11.0&#39;&#34;:&#xA;&#x9;* .github/workflows/microbenchmark.yml&#xA;</p>
<details>
<summary>8.11.0</summary>
<pre>&#xA;Release published on the 2023-11-07 16:09:10 +0000 UTC at the url https://github.com/elastic/elasticsearch/releases/tag/v8.11.0&#xA;&#xA;Downloads: https://elastic.co/downloads/elasticsearch&#xA;Release notes: https://www.elastic.co/guide/en/elasticsearch/reference/8.11/release-notes-8.11.0.html</pre>
</details>
<details>
<summary>8.11.1</summary>
<pre>&#xA;Release …
> [updatecli] Bump elastic stack version to 8.11.3

- .github/workflows/ci.yml
- .github/workflows/microbenchmark.yml
<Actions>
<summary>Update elastic stack version to 8.12.0</summary>
<p>1 file(s) updated with &#34;&#39;8.12.0&#39;&#34;:&#xA;&#x9;* .github/workflows/microbenchmark.yml&#xA;</p>
<details>
<summary>8.12.0</summary>
<pre>&#xA;Release published on the 2024-01-17 15:39:27 +0000 UTC at the url https://github.com/elastic/elasticsearch/releases/tag/v8.12.0&#xA;&#xA;Downloads: https://elastic.co/downloads/elasticsearch&#xA;Release notes: https://www.elastic.co/guide/en/elasticsearch/reference/main/release-notes-8.12.0.html</pre>
</details>
</details>
<details …
> [updatecli] Bump elastic stack version to 8.12.0

- .github/workflows/ci.yml
- .github/workflows/microbenchmark.yml
<Actions>
<summary>Update elastic stack version to 8.12.1</summary>
<p>1 file(s) updated with &#34;&#39;8.12.1&#39;&#34;:&#xA;&#x9;* .github/workflows/microbenchmark.yml&#xA;</p>
<details>
<summary>8.12.1</summary>
<pre>&#xA;Release published on the 2024-02-06 12:46:25 +0000 UTC at the url https://github.com/elastic/elasticsearch/releases/tag/v8.12.1&#xA;&#xA;Downloads: https://elastic.co/downloads/elasticsearch&#xA;Release notes: https://www.elastic.co/guide/en/elasticsearch/reference/8.12/release-notes-8.12.1.html</pre>
</details>
<details>
<summary>8.12.2</summary>
<pre>&#xA;Release …
> [updatecli] Bump elastic stack version to 8.12.2

- .github/workflows/ci.yml
- .github/workflows/microbenchmark.yml
<Actions>
<summary>Update elastic stack version to 8.13.0</summary>
<p>1 file(s) updated with &#34;&#39;8.13.0&#39;&#34;:&#xA;&#x9;* .github/workflows/microbenchmark.yml&#xA;</p>
<details>
<summary>8.13.0</summary>
<pre>&#xA;Release published on the 2024-03-26 16:13:02 +0000 UTC at the url https://github.com/elastic/elasticsearch/releases/tag/v8.13.0&#xA;&#xA;Downloads: https://elastic.co/downloads/elasticsearch&#xA;Release notes: https://www.elastic.co/guide/en/elasticsearch/reference/8.13/release-notes-8.13.0.html</pre>
</details>
</details>
<details …
> [updatecli] Bump elastic stack version to 8.13.0

- .github/workflows/ci.yml
- .github/workflows/microbenchmark.yml
<Actions>
<summary>Update elastic stack version to 8.13.4</summary>
<p>1 file(s) updated with &#34;&#39;8.13.4&#39;&#34;:&#xA;&#x9;* .github/workflows/microbenchmark.yml&#xA;</p>
<details>
<summary>8.13.3</summary>
<pre>&#xA;Release published on the 2024-05-03 10:43:13 +0000 UTC at the url https://github.com/elastic/elasticsearch/releases/tag/v8.13.3&#xA;&#xA;Downloads: https://elastic.co/downloads/elasticsearch&#xA;Release notes: https://www.elastic.co/guide/en/elasticsearch/reference/8.13/release-notes-8.13.3.html</pre>
</details>
<details>
<summary>8.13.4</summary>
<pre>&#xA;Release …
> [updatecli] Bump elastic stack version to 8.13.4

- .github/workflows/ci.yml
- .github/workflows/microbenchmark.yml
<Actions>
<summary>Update elastic stack version to 8.14.1</summary>
<p>1 file(s) updated with &#34;&#39;8.14.1&#39;&#34;:&#xA;&#x9;* .github/workflows/ci.yml&#xA;</p>
<details>
<summary>8.14.1</summary>
<pre>&#xA;Release published on the 2024-06-12 14:37:46 +0000 UTC at the url https://github.com/elastic/elasticsearch/releases/tag/v8.14.1&#xA;&#xA;Downloads: https://elastic.co/downloads/elasticsearch&#xA;Release notes: https://www.elastic.co/guide/en/elasticsearch/reference/main/release-notes-8.14.1.html</pre>
</details>
</details>
<details …
> [updatecli] Bump elastic stack version to 8.14.1

- CHANGELOG.asciidoc
> docs: update 5.16.1 release notes

- CHANGELOG.asciidoc
Update 5.x with the changes made in https://github.com/elastic/apm-agent-rum-js/pull/1514
> docs: update 5.16.1 release notes (#1514)

- .github/workflows/bump-elastic-stack.yml
I tested it in https://github.com/elastic/apm-agent-rum-js/actions/runs/10923956949
> chore: updatecli permissions to change workflows

- scripts/ci-release.mjs
A leftover from https://github.com/elastic/apm-agent-rum-js/pull/1519
> ci(release): remove totp

- scripts/ci-pre-release.mjs
> ci: use prerelease so no branch protection issues

- lerna.json
> ci: lerna allow prerelease branches

- docs/release-notes/breaking-changes.md
- docs/release-notes/known-issues.md
Updates the navigation titles for the release notes.
> Updates navigation titles for release notes

- docs/reference/install-agent.md
+ fix https://github.com/elastic/apm-agent-rum-js/issues/1611
> docs: update agent install instructions
